export const VENDOR_RESTAURANT_DASHBOARD_DATA = {
    "message": {
      "2020-11-27": [
        {
          "date": "2020-11-04",
          "id": 125,
          "order_subtotal": "2940.00",
          "order_discount": "0.00",
          "order_grandtotal": "3439.81",
          "order_no": "22817",
          "order_type": "delivery",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-11-04 19:33:28",
          "created_at": "2020-11-04 15:33:29",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "499.80",
          "estimated_time": "180",
          "status": "Completed",
          "order_status_display_vendor": "Completed",
          "order_status_display_user": "Completed"
        }
      ],
      "2020-11-26": [
        {
          "date": "2020-03-03",
          "id": 139,
          "order_subtotal": "152.00",
          "order_discount": "0.00",
          "order_grandtotal": "177.85",
          "order_no": "92655",
          "order_type": "take_away",
          "customer_fname": "Haris Mahmoud",
          "customer_lname": "Haris Mahmoud",
          "customer_address1": "Circular Quay East, Sydney, Australia",
          "customer_address2": "Circular Quay East, Sydney, Australia",
          "customer_city": "Sydney",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2000",
          "view_admin": 0,
          "pickup_time": "2020-03-03 18:04:00",
          "created_at": "2020-03-03 07:03:29",
          "order_shipping": "0",
          "address_id": 224,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "25.84",
          "estimated_time": "20",
          "status": "Accepted",
          "order_status_display_vendor": "Accepted",
          "order_status_display_user": "Accepted"
        },
        {
          "date": "2020-03-03",
          "id": 141,
          "order_subtotal": "28.00",
          "order_discount": "0.00",
          "order_grandtotal": "32.77",
          "order_no": "24608",
          "order_type": "take_away",
          "customer_fname": "Haris Mahmoud",
          "customer_lname": "Haris Mahmoud",
          "customer_address1": "Circular Quay East, Sydney, Australia",
          "customer_address2": "Circular Quay East, Sydney, Australia",
          "customer_city": "Sydney",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2000",
          "view_admin": 0,
          "pickup_time": "2020-03-04 13:13:00",
          "created_at": "2020-03-03 08:15:43",
          "order_shipping": "0",
          "address_id": 225,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "4.76",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-03",
          "id": 154,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "10720",
          "order_type": "delivery",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-03 15:56:05",
          "created_at": "2020-03-03 10:56:06",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-03",
          "id": 157,
          "order_subtotal": "28.00",
          "order_discount": "0.00",
          "order_grandtotal": "32.77",
          "order_no": "21443",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-03 17:24:27",
          "created_at": "2020-03-03 11:54:28",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "4.76",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-03",
          "id": 158,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "39959",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-03 17:44:15",
          "created_at": "2020-03-03 12:14:16",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-03",
          "id": 159,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "93619",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-03 17:44:57",
          "created_at": "2020-03-03 12:14:58",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-03",
          "id": 160,
          "order_subtotal": "28.00",
          "order_discount": "0.00",
          "order_grandtotal": "32.77",
          "order_no": "82286",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-03 17:45:50",
          "created_at": "2020-03-03 12:15:51",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "4.76",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-03",
          "id": 161,
          "order_subtotal": "10.00",
          "order_discount": "0.00",
          "order_grandtotal": "11.71",
          "order_no": "39601",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-03 17:46:45",
          "created_at": "2020-03-03 12:16:46",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "1.70",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-03",
          "id": 162,
          "order_subtotal": "28.00",
          "order_discount": "0.00",
          "order_grandtotal": "32.77",
          "order_no": "35980",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-03 17:53:31",
          "created_at": "2020-03-03 12:23:32",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "4.76",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-03",
          "id": 164,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "99993",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-03 17:55:59",
          "created_at": "2020-03-03 12:25:59",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-03",
          "id": 166,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "81410",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-03 18:05:05",
          "created_at": "2020-03-03 12:35:06",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-03",
          "id": 167,
          "order_subtotal": "28.00",
          "order_discount": "0.00",
          "order_grandtotal": "32.77",
          "order_no": "43095",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-03 18:15:06",
          "created_at": "2020-03-03 12:45:07",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmod",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "4.76",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-03",
          "id": 168,
          "order_subtotal": "110.00",
          "order_discount": "0.00",
          "order_grandtotal": "128.71",
          "order_no": "52135",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-03 18:16:16",
          "created_at": "2020-03-03 12:46:17",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Vijay",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "18.70",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-03",
          "id": 169,
          "order_subtotal": "28.00",
          "order_discount": "0.00",
          "order_grandtotal": "32.77",
          "order_no": "83555",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-03 18:18:29",
          "created_at": "2020-03-03 12:48:30",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Vijay",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "4.76",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-03",
          "id": 170,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "11167",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-03 18:20:54",
          "created_at": "2020-03-03 12:50:55",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-03",
          "id": 171,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "80774",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-03 18:26:01",
          "created_at": "2020-03-03 12:56:01",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Vijay",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-03",
          "id": 173,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "82794",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-03 18:29:05",
          "created_at": "2020-03-03 12:59:05",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Vijay",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        }
      ],
      "2020-03-05": [
        {
          "date": "2020-03-05",
          "id": 178,
          "order_subtotal": "1960.00",
          "order_discount": "0.00",
          "order_grandtotal": "2293.21",
          "order_no": "36760",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-05 15:25:54",
          "created_at": "2020-03-05 10:25:54",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "333.20",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-05",
          "id": 180,
          "order_subtotal": "48.00",
          "order_discount": "0.00",
          "order_grandtotal": "56.17",
          "order_no": "48437",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-05 15:29:03",
          "created_at": "2020-03-05 10:29:03",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "8.16",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-05",
          "id": 182,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "84396",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-05 16:02:36",
          "created_at": "2020-03-05 10:32:37",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-05",
          "id": 184,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "94030",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-05 16:24:39",
          "created_at": "2020-03-05 10:54:40",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-05",
          "id": 186,
          "order_subtotal": "112.00",
          "order_discount": "0.00",
          "order_grandtotal": "131.05",
          "order_no": "22690",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-05 16:35:54",
          "created_at": "2020-03-05 11:05:55",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "19.04",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-05",
          "id": 187,
          "order_subtotal": "152.00",
          "order_discount": "0.00",
          "order_grandtotal": "177.85",
          "order_no": "49562",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-05 16:38:01",
          "created_at": "2020-03-05 11:08:02",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "25.84",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-05",
          "id": 189,
          "order_subtotal": "1008.00",
          "order_discount": "0.00",
          "order_grandtotal": "1179.38",
          "order_no": "35454",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-05 17:14:45",
          "created_at": "2020-03-05 11:44:47",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "171.36",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-05",
          "id": 190,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "35398",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-05 17:19:23",
          "created_at": "2020-03-05 11:49:23",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-05",
          "id": 192,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "23471",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-05 17:22:02",
          "created_at": "2020-03-05 11:52:03",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-05",
          "id": 193,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "56338",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-05 17:25:44",
          "created_at": "2020-03-05 11:55:45",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-05",
          "id": 195,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "86017",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-05 17:30:29",
          "created_at": "2020-03-05 12:00:29",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-05",
          "id": 196,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "88160",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-05 17:35:06",
          "created_at": "2020-03-05 12:05:07",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-05",
          "id": 198,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "55136",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-05 17:36:47",
          "created_at": "2020-03-05 12:06:47",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-05",
          "id": 200,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "72902",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-05 17:39:02",
          "created_at": "2020-03-05 12:09:03",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-05",
          "id": 205,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "89305",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-05 18:54:16",
          "created_at": "2020-03-05 13:24:17",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-05",
          "id": 208,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "34307",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-05 19:00:11",
          "created_at": "2020-03-05 13:30:12",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        }
      ],
      "2020-11-06": [
        {
          "date": "2020-03-06",
          "id": 212,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "18212",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-06 09:51:54",
          "created_at": "2020-03-06 04:21:52",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-06",
          "id": 215,
          "order_subtotal": "1130.00",
          "order_discount": "0.00",
          "order_grandtotal": "1322.13",
          "order_no": "53320",
          "order_type": "take_away",
          "customer_fname": "Haris Mahmoud",
          "customer_lname": "Haris Mahmoud",
          "customer_address1": "Circular Quay East, Sydney, Australia",
          "customer_address2": "Circular Quay East, Sydney, Australia",
          "customer_city": "Sydney",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2000",
          "view_admin": 0,
          "pickup_time": "2020-03-24 18:03:00",
          "created_at": "2020-03-06 07:03:36",
          "order_shipping": "0",
          "address_id": 232,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "192.10",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-06",
          "id": 216,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "18972",
          "order_type": "delivery",
          "customer_fname": "Haris Mahmoud",
          "customer_lname": "Haris Mahmoud",
          "customer_address1": "Circular Quay East, Sydney, Australia",
          "customer_address2": "Circular Quay East, Sydney, Australia",
          "customer_city": "Sydney",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2000",
          "view_admin": 0,
          "pickup_time": "2020-03-06 01:01:00",
          "created_at": "2020-03-06 07:31:10",
          "order_shipping": "0",
          "address_id": 233,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-06",
          "id": 217,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "36358",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-06 13:12:22",
          "created_at": "2020-03-06 07:42:35",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-06",
          "id": 218,
          "order_subtotal": "28.00",
          "order_discount": "0.00",
          "order_grandtotal": "32.77",
          "order_no": "97201",
          "order_type": "delivery",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-06 13:15:54",
          "created_at": "2020-03-06 07:45:55",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "4.76",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-06",
          "id": 219,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "83080",
          "order_type": "delivery",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-06 13:20:45",
          "created_at": "2020-03-06 07:50:46",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-06",
          "id": 220,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "52787",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-06 13:35:14",
          "created_at": "2020-03-06 08:05:15",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-06",
          "id": 221,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "36289",
          "order_type": "delivery",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-06 13:35:55",
          "created_at": "2020-03-06 08:05:56",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-06",
          "id": 223,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "12982",
          "order_type": "delivery",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-06 13:45:04",
          "created_at": "2020-03-06 08:15:06",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-06",
          "id": 225,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "99256",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-06 13:48:39",
          "created_at": "2020-03-06 08:18:40",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-06",
          "id": 226,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "75793",
          "order_type": "delivery",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-06 13:57:11",
          "created_at": "2020-03-06 08:27:12",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-06",
          "id": 229,
          "order_subtotal": "1008.00",
          "order_discount": "0.00",
          "order_grandtotal": "1179.38",
          "order_no": "54951",
          "order_type": "delivery",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-06 15:15:20",
          "created_at": "2020-03-06 09:45:20",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "171.36",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-06",
          "id": 231,
          "order_subtotal": "28.00",
          "order_discount": "0.00",
          "order_grandtotal": "32.77",
          "order_no": "58361",
          "order_type": "delivery",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-06 15:28:50",
          "created_at": "2020-03-06 09:58:51",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "4.76",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-06",
          "id": 232,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "42949",
          "order_type": "delivery",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-06 15:32:22",
          "created_at": "2020-03-06 10:02:23",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-06",
          "id": 233,
          "order_subtotal": "980.00",
          "order_discount": "0.00",
          "order_grandtotal": "1146.61",
          "order_no": "69735",
          "order_type": "delivery",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-06 15:33:57",
          "created_at": "2020-03-06 10:03:57",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "166.60",
          "estimated_time": "60",
          "status": "Accepted",
          "order_status_display_vendor": "Accepted",
          "order_status_display_user": "Accepted"
        },
        {
          "date": "2020-03-06",
          "id": 234,
          "order_subtotal": "1218.00",
          "order_discount": "0.00",
          "order_grandtotal": "1425.10",
          "order_no": "94631",
          "order_type": "delivery",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-06 15:44:56",
          "created_at": "2020-03-06 10:14:57",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "207.06",
          "estimated_time": "",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed"
        },
        {
          "date": "2020-03-06",
          "id": 236,
          "order_subtotal": "1960.00",
          "order_discount": "0.00",
          "order_grandtotal": "2293.21",
          "order_no": "84823",
          "order_type": "take_away",
          "customer_fname": "Haris Mahmoud",
          "customer_lname": "Haris Mahmoud",
          "customer_address1": "Circular Quay East, Sydney, Australia",
          "customer_address2": "Circular Quay East, Sydney, Australia",
          "customer_city": "Sydney",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2000",
          "view_admin": 0,
          "pickup_time": "2020-03-06 15:35:00",
          "created_at": "2020-03-06 10:35:54",
          "order_shipping": "0",
          "address_id": 234,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "333.20",
          "estimated_time": "10",
          "status": "Accepted",
          "order_status_display_vendor": "Accepted",
          "order_status_display_user": "Accepted"
        },
        {
          "date": "2020-03-06",
          "id": 237,
          "order_subtotal": "336.00",
          "order_discount": "0.00",
          "order_grandtotal": "393.13",
          "order_no": "20540",
          "order_type": "take_away",
          "customer_fname": "ankhon k sageerr ledobe hmeeenn tarapna meraaa dharkan meriiiii",
          "customer_lname": "ankhon k sageerr ledobe hmeeenn tarapna meraaa dharkan meriiiii",
          "customer_address1": "Circular Quay East, Sydney, Australia",
          "customer_address2": "Circular Quay East, Sydney, Australia",
          "customer_city": "Sydney",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2000",
          "view_admin": 0,
          "pickup_time": "2020-03-06 16:59:00",
          "created_at": "2020-03-06 12:00:22",
          "order_shipping": "0",
          "address_id": 235,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "57.12",
          "estimated_time": "50",
          "status": "Accepted",
          "order_status_display_vendor": "Accepted",
          "order_status_display_user": "Accepted"
        }
      ],
      "2020-11-07": [
        {
          "date": "2020-03-10",
          "id": 238,
          "order_subtotal": "1620.00",
          "order_discount": "0.00",
          "order_grandtotal": "1895.42",
          "order_no": "74101",
          "order_type": "take_away",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "view_admin": 0,
          "pickup_time": "2020-03-11 09:31:53",
          "created_at": "2020-03-10 22:31:53",
          "order_shipping": "0",
          "address_id": 171,
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "seller_id": 892,
          "seller_paypal_email": null,
          "ship_cost": "0.00",
          "order_gst_amount": "275.40",
          "estimated_time": "20",
          "status": "Accepted",
          "order_status_display_vendor": "Accepted",
          "order_status_display_user": "Accepted"
        }
      ]
    }
  };

  export const RESTAURANT_ORDER_LIST = {
    "data": {
      "orders": [
        {
          "id": 238,
          "user_id": 482,
          "order_subtotal": "1620.00",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "order_no": "74101",
          "order_type": "take_away",
          "order_grandtotal": "1895.42",
          "created_at": "2020-03-10 22:31:53",
          "estimated_time": "180",
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "status": "Accepted",
          "order_status_display_vendor": "Accepted",
          "order_status_display_user": "Accepted",
          "current_status": {
            "id": 773,
            "restaurant_orders_id": 238,
            "status": "confirmed",
            "current_status": "1",
            "created_at": "2020-03-10 22:32:07",
            "updated_at": "2020-11-06 18:18:28",
            "changed_at": "2020-03-18 13:18:28"
          }
        },
        {
          "id": 237,
          "user_id": 482,
          "order_subtotal": "336.00",
          "customer_fname": "ankhon k sageerr ledobe hmeeenn tarapna meraaa dharkan meriiiii",
          "customer_lname": "ankhon k sageerr ledobe hmeeenn tarapna meraaa dharkan meriiiii",
          "customer_address1": "Circular Quay East, Sydney, Australia",
          "customer_address2": "Circular Quay East, Sydney, Australia",
          "customer_city": "Sydney",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2000",
          "order_no": "20540",
          "order_type": "take_away",
          "order_grandtotal": "393.13",
          "created_at": "2020-03-06 12:00:22",
          "estimated_time": "50",
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "status": "Accepted",
          "order_status_display_vendor": "Accepted",
          "order_status_display_user": "Accepted",
          "current_status": {
            "id": 768,
            "restaurant_orders_id": 237,
            "status": "confirmed",
            "current_status": "1",
            "created_at": "2020-03-06 12:00:26",
            "updated_at": "2020-03-12 07:43:49",
            "changed_at": "2020-03-12 07:43:49"
          }
        },
        {
          "id": 236,
          "user_id": 482,
          "order_subtotal": "1960.00",
          "customer_fname": "Haris Mahmoud",
          "customer_lname": "Haris Mahmoud",
          "customer_address1": "Circular Quay East, Sydney, Australia",
          "customer_address2": "Circular Quay East, Sydney, Australia",
          "customer_city": "Sydney",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2000",
          "order_no": "84823",
          "order_type": "take_away",
          "order_grandtotal": "2293.21",
          "created_at": "2020-03-06 10:35:54",
          "estimated_time": "10",
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "status": "Accepted",
          "order_status_display_vendor": "Accepted",
          "order_status_display_user": "Accepted",
          "current_status": {
            "id": 763,
            "restaurant_orders_id": 236,
            "status": "confirmed",
            "current_status": "1",
            "created_at": "2020-03-06 10:35:58",
            "updated_at": "2020-03-18 13:20:53",
            "changed_at": "2020-03-18 13:20:53"
          }
        },
        {
          "id": 234,
          "user_id": 482,
          "order_subtotal": "1218.00",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "order_no": "94631",
          "order_type": "delivery",
          "order_grandtotal": "1425.10",
          "created_at": "2020-03-06 10:14:57",
          "estimated_time": "",
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed",
          "current_status": {
            "id": 757,
            "restaurant_orders_id": 234,
            "status": "order-received",
            "current_status": "1",
            "created_at": "2020-03-06 10:15:00",
            "updated_at": "2020-03-06 10:15:00",
            "changed_at": "2020-03-06 10:15:00"
          }
        },
        {
          "id": 233,
          "user_id": 482,
          "order_subtotal": "980.00",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "order_no": "69735",
          "order_type": "delivery",
          "order_grandtotal": "1146.61",
          "created_at": "2020-03-06 10:03:57",
          "estimated_time": "",
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed",
          "current_status": {
            "id": 752,
            "restaurant_orders_id": 233,
            "status": "order-received",
            "current_status": "1",
            "created_at": "2020-03-06 10:04:00",
            "updated_at": "2020-03-06 10:04:00",
            "changed_at": "2020-03-06 10:04:00"
          }
        },
        {
          "id": 232,
          "user_id": 482,
          "order_subtotal": "980.00",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "order_no": "42949",
          "order_type": "delivery",
          "order_grandtotal": "1146.61",
          "created_at": "2020-03-06 10:02:23",
          "estimated_time": "",
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed",
          "current_status": {
            "id": 747,
            "restaurant_orders_id": 232,
            "status": "order-received",
            "current_status": "1",
            "created_at": "2020-03-06 10:02:26",
            "updated_at": "2020-03-06 10:02:26",
            "changed_at": "2020-03-06 10:02:26"
          }
        },
        {
          "id": 231,
          "user_id": 482,
          "order_subtotal": "28.00",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "order_no": "58361",
          "order_type": "delivery",
          "order_grandtotal": "32.77",
          "created_at": "2020-03-06 09:58:51",
          "estimated_time": "",
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed",
          "current_status": {
            "id": 742,
            "restaurant_orders_id": 231,
            "status": "order-received",
            "current_status": "1",
            "created_at": "2020-03-06 09:58:53",
            "updated_at": "2020-03-06 09:58:53",
            "changed_at": "2020-03-06 09:58:53"
          }
        },
        {
          "id": 230,
          "user_id": 482,
          "order_subtotal": "980.00",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "order_no": "30221",
          "order_type": "delivery",
          "order_grandtotal": "1146.61",
          "created_at": "2020-03-06 09:54:22",
          "estimated_time": "",
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed",
          "current_status": {
            "id": 737,
            "restaurant_orders_id": 230,
            "status": "order-received",
            "current_status": "1",
            "created_at": "2020-03-06 09:54:25",
            "updated_at": "2020-03-06 09:54:25",
            "changed_at": "2020-03-06 09:54:25"
          }
        },
        {
          "id": 229,
          "user_id": 482,
          "order_subtotal": "1008.00",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "order_no": "54951",
          "order_type": "delivery",
          "order_grandtotal": "1179.38",
          "created_at": "2020-03-06 09:45:20",
          "estimated_time": "",
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed",
          "current_status": {
            "id": 732,
            "restaurant_orders_id": 229,
            "status": "order-received",
            "current_status": "1",
            "created_at": "2020-03-06 09:45:23",
            "updated_at": "2020-03-06 09:45:23",
            "changed_at": "2020-03-06 09:45:23"
          }
        },
        {
          "id": 226,
          "user_id": 482,
          "order_subtotal": "980.00",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "order_no": "75793",
          "order_type": "delivery",
          "order_grandtotal": "1146.61",
          "created_at": "2020-03-06 08:27:12",
          "estimated_time": "",
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed",
          "current_status": {
            "id": 727,
            "restaurant_orders_id": 226,
            "status": "order-received",
            "current_status": "1",
            "created_at": "2020-03-06 08:27:14",
            "updated_at": "2020-03-06 08:27:14",
            "changed_at": "2020-03-06 08:27:14"
          }
        },
        {
          "id": 238,
          "user_id": 482,
          "order_subtotal": "1620.00",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "order_no": "74101",
          "order_type": "take_away",
          "order_grandtotal": "1895.42",
          "created_at": "2020-03-10 22:31:53",
          "estimated_time": "300",
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "status": "Accepted",
          "order_status_display_vendor": "Accepted",
          "order_status_display_user": "Accepted",
          "current_status": {
            "id": 773,
            "restaurant_orders_id": 238,
            "status": "confirmed",
            "current_status": "1",
            "created_at": "2020-03-10 22:32:07",
            "updated_at": "2020-11-05 11:30:28",
            "changed_at": "2020-03-18 13:18:28"
          }
        },
        {
          "id": 237,
          "user_id": 482,
          "order_subtotal": "336.00",
          "customer_fname": "ankhon k sageerr ledobe hmeeenn tarapna meraaa dharkan meriiiii",
          "customer_lname": "ankhon k sageerr ledobe hmeeenn tarapna meraaa dharkan meriiiii",
          "customer_address1": "Circular Quay East, Sydney, Australia",
          "customer_address2": "Circular Quay East, Sydney, Australia",
          "customer_city": "Sydney",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2000",
          "order_no": "20540",
          "order_type": "take_away",
          "order_grandtotal": "393.13",
          "created_at": "2020-03-06 12:00:22",
          "estimated_time": "50",
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "status": "Accepted",
          "order_status_display_vendor": "Accepted",
          "order_status_display_user": "Accepted",
          "current_status": {
            "id": 768,
            "restaurant_orders_id": 237,
            "status": "confirmed",
            "current_status": "1",
            "created_at": "2020-03-06 12:00:26",
            "updated_at": "2020-03-12 07:43:49",
            "changed_at": "2020-03-12 07:43:49"
          }
        },
        {
          "id": 236,
          "user_id": 482,
          "order_subtotal": "1960.00",
          "customer_fname": "Haris Mahmoud",
          "customer_lname": "Haris Mahmoud",
          "customer_address1": "Circular Quay East, Sydney, Australia",
          "customer_address2": "Circular Quay East, Sydney, Australia",
          "customer_city": "Sydney",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2000",
          "order_no": "84823",
          "order_type": "take_away",
          "order_grandtotal": "2293.21",
          "created_at": "2020-03-06 10:35:54",
          "estimated_time": "10",
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "status": "Accepted",
          "order_status_display_vendor": "Accepted",
          "order_status_display_user": "Accepted",
          "current_status": {
            "id": 763,
            "restaurant_orders_id": 236,
            "status": "confirmed",
            "current_status": "1",
            "created_at": "2020-03-06 10:35:58",
            "updated_at": "2020-03-18 13:20:53",
            "changed_at": "2020-03-18 13:20:53"
          }
        },
        {
          "id": 234,
          "user_id": 482,
          "order_subtotal": "1218.00",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "order_no": "94631",
          "order_type": "delivery",
          "order_grandtotal": "1425.10",
          "created_at": "2020-03-06 10:14:57",
          "estimated_time": "",
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed",
          "current_status": {
            "id": 757,
            "restaurant_orders_id": 234,
            "status": "order-received",
            "current_status": "1",
            "created_at": "2020-03-06 10:15:00",
            "updated_at": "2020-03-06 10:15:00",
            "changed_at": "2020-03-06 10:15:00"
          }
        },
        {
          "id": 233,
          "user_id": 482,
          "order_subtotal": "980.00",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "order_no": "69735",
          "order_type": "delivery",
          "order_grandtotal": "1146.61",
          "created_at": "2020-03-06 10:03:57",
          "estimated_time": "",
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed",
          "current_status": {
            "id": 752,
            "restaurant_orders_id": 233,
            "status": "order-received",
            "current_status": "1",
            "created_at": "2020-03-06 10:04:00",
            "updated_at": "2020-03-06 10:04:00",
            "changed_at": "2020-03-06 10:04:00"
          }
        },
        {
          "id": 232,
          "user_id": 482,
          "order_subtotal": "980.00",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "order_no": "42949",
          "order_type": "delivery",
          "order_grandtotal": "1146.61",
          "created_at": "2020-03-06 10:02:23",
          "estimated_time": "",
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed",
          "current_status": {
            "id": 747,
            "restaurant_orders_id": 232,
            "status": "order-received",
            "current_status": "1",
            "created_at": "2020-03-06 10:02:26",
            "updated_at": "2020-03-06 10:02:26",
            "changed_at": "2020-03-06 10:02:26"
          }
        },
        {
          "id": 231,
          "user_id": 482,
          "order_subtotal": "28.00",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "order_no": "58361",
          "order_type": "delivery",
          "order_grandtotal": "32.77",
          "created_at": "2020-03-06 09:58:51",
          "estimated_time": "",
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed",
          "current_status": {
            "id": 742,
            "restaurant_orders_id": 231,
            "status": "order-received",
            "current_status": "1",
            "created_at": "2020-03-06 09:58:53",
            "updated_at": "2020-03-06 09:58:53",
            "changed_at": "2020-03-06 09:58:53"
          }
        },
        {
          "id": 230,
          "user_id": 482,
          "order_subtotal": "980.00",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "order_no": "30221",
          "order_type": "delivery",
          "order_grandtotal": "1146.61",
          "created_at": "2020-03-06 09:54:22",
          "estimated_time": "",
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed",
          "current_status": {
            "id": 737,
            "restaurant_orders_id": 230,
            "status": "order-received",
            "current_status": "1",
            "created_at": "2020-03-06 09:54:25",
            "updated_at": "2020-03-06 09:54:25",
            "changed_at": "2020-03-06 09:54:25"
          }
        },
        {
          "id": 229,
          "user_id": 482,
          "order_subtotal": "1008.00",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "order_no": "54951",
          "order_type": "delivery",
          "order_grandtotal": "1179.38",
          "created_at": "2020-03-06 09:45:20",
          "estimated_time": "",
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed",
          "current_status": {
            "id": 732,
            "restaurant_orders_id": 229,
            "status": "order-received",
            "current_status": "1",
            "created_at": "2020-03-06 09:45:23",
            "updated_at": "2020-03-06 09:45:23",
            "changed_at": "2020-03-06 09:45:23"
          }
        },
        {
          "id": 226,
          "user_id": 482,
          "order_subtotal": "980.00",
          "customer_fname": "javed",
          "customer_lname": "iqbal",
          "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
          "customer_address2": "",
          "customer_city": "Riverstone",
          "customer_state": "New South Wales",
          "customer_country": "Australia",
          "customer_postcode": "2765",
          "order_no": "75793",
          "order_type": "delivery",
          "order_grandtotal": "1146.61",
          "created_at": "2020-03-06 08:27:12",
          "estimated_time": "",
          "name": "Haris Mahmoud",
          "phone_number": "3164814847",
          "status": "Accepted-Paid",
          "order_status_display_vendor": "Pending",
          "order_status_display_user": "Payment Confirmed",
          "current_status": {
            "id": 727,
            "restaurant_orders_id": 226,
            "status": "order-received",
            "current_status": "1",
            "created_at": "2020-03-06 08:27:14",
            "updated_at": "2020-03-06 08:27:14",
            "changed_at": "2020-03-06 08:27:14"
          }
        }
      ],
      "menu_id": 1
    },
    "staus": "success",
    "status_code": 200,
    "message": "Orders fetched successfully."
  }
 