export const  BOOKING_LIST = [
      {
        "id": 645,
        "trader_user_id": 657,
        "trader_profile_id": 140,
        "customer_id": 482,
        "booking_cat_id": 2,
        "booking_sub_cat_id": 13,
        "type": "beauty",
        "name": "Muzammil",
        "phone_number": null,
        "date_of_birth": "2009-09-09",
        "cost": 0,
        "status": "Pending",
        "created_at": "2020-02-13 10:19:55",
        "updated_at": "2020-02-28 07:01:38",
        "gender": "male",
        "booking_date": "2019-12-19",
        "start_time": "19:00:00",
        "end_time": "19:00:00",
        "additional_comments": null,
        "commission_percentage": 10,
        "gst_percentage": 0,
        "stripe_transaction_fee": "0",
        "stripe_payment_intent_id": null,
        "stripe_payment_intent_status": null,
        "prepay_id": null,
        "paylinx_order_no": null,
        "out_trade_no": null,
        "sign": null,
        "alipay_qr": null,
        "paylinx_payment_status": null,
        "deleted_at": null,
        "notify_user_count": 0,
        "trader_rating": "4.8000",
        "valid_trader_rating_count": 10,
        "duration": 0,
        "tax_amount": 0,
        "commission_amount": 0,
        "total_amount": 0,
        "service_sub_bookings": [],
        "trader_user_profile": {
          "id": 140,
          "user_id": 657,
          "service_type": null
        },
        "trader_user": {
          "id": 657,
          "business_name": "Ammar vendo",
          "business_location": "145 Boundary Rd, North Melbourne VIC 3051, Australia",
          "image": "http://localhost/upload_images/users/657/77100.jpg",
          "business_state_id": "Victoria",
          "business_city_id": "North Melbourne"
        },
        "valid_trader_rating": null
      },
      {
        "id": 120,
        "trader_user_id": 922,
        "trader_profile_id": 220,
        "customer_id": 482,
        "booking_cat_id": 49,
        "booking_sub_cat_id": 41,
        "type": "beauty",
        "name": "Talha",
        "phone_number": "+921231234567",
        "date_of_birth": null,
        "cost": 1000,
        "status": "Payment-Error",
        "created_at": "2019-09-13 13:35:55",
        "updated_at": "2019-12-24 14:28:02",
        "gender": null,
        "booking_date": "2019-09-16",
        "start_time": "17:00:00",
        "end_time": "18:00:00",
        "additional_comments": null,
        "commission_percentage": 10,
        "gst_percentage": 0,
        "stripe_transaction_fee": "0",
        "stripe_payment_intent_id": null,
        "stripe_payment_intent_status": null,
        "prepay_id": null,
        "paylinx_order_no": null,
        "out_trade_no": null,
        "sign": null,
        "alipay_qr": null,
        "paylinx_payment_status": null,
        "deleted_at": null,
        "notify_user_count": 0,
        "trader_rating": "3.0000",
        "valid_trader_rating_count": 1,
        "duration": 60,
        "tax_amount": 0,
        "commission_amount": 100,
        "total_amount": 1100,
        "service_sub_bookings": [
          {
            "id": 140,
            "trader_user_id": 922,
            "trader_profile_id": 237,
            "customer_id": 705,
            "service_booking_id": 120,
            "wellbeing_trader_service_id": 94,
            "booking_date": "2019-09-16",
            "start_time": "17:00:00",
            "end_time": "17:30:00",
            "cost": 500,
            "created_at": "2019-09-13 13:35:55",
            "updated_at": "2019-09-13 13:35:55",
            "duration": 30,
            "wellbeing_trader_service": {
              "id": 94,
              "name": "Bsic makeup"
            }
          },
          {
            "id": 141,
            "trader_user_id": 922,
            "trader_profile_id": 237,
            "customer_id": 705,
            "service_booking_id": 120,
            "wellbeing_trader_service_id": 112,
            "booking_date": "2019-09-16",
            "start_time": "17:30:00",
            "end_time": "18:00:00",
            "cost": 500,
            "created_at": "2019-09-13 13:35:55",
            "updated_at": "2019-09-13 13:35:55",
            "duration": 30,
            "wellbeing_trader_service": {
              "id": 112,
              "name": "part mackup"
            }
          }
        ],
        "trader_user_profile": {
          "id": 220,
          "user_id": 892,
          "service_type": "25"
        },
        "trader_user": {
          "id": 922,
          "business_name": "Derma lab & beauty therapy",
          "business_location": "Melbourne",
          "image": "http://localhost/upload_images/users/922/14757.jpg",
          "business_state_id": "ABC state",
          "business_city_id": "ABC city"
        },
        "valid_trader_rating": null
      }
    ]
 
    export const BOOKING_HISTORY = [
          {
            "id": 316,
            "trader_user_id": 913,
            "trader_profile_id": 230,
            "customer_id": 922,
            "booking_cat_id": 3,
            "booking_sub_cat_id": 40,
            "type": "beauty",
            "name": "Talha Naeem",
            "phone_number": "03214069167",
            "date_of_birth": null,
            "cost": 5975,
            "status": "Completed",
            "created_at": "2019-09-26 20:16:54",
            "updated_at": "2019-09-26 20:18:10",
            "gender": null,
            "booking_date": "2019-09-30",
            "start_time": "21:00:00",
            "end_time": "23:00:00",
            "additional_comments": "hi",
            "commission_percentage": 10,
            "gst_percentage": 0,
            "stripe_transaction_fee": "0",
            "stripe_payment_intent_id": null,
            "stripe_payment_intent_status": null,
            "prepay_id": null,
            "paylinx_order_no": null,
            "out_trade_no": null,
            "sign": null,
            "alipay_qr": null,
            "paylinx_payment_status": null,
            "deleted_at": null,
            "notify_user_count": 0,
            "trader_rating": "4.2667",
            "valid_trader_rating_count": 15,
            "duration": 120,
            "tax_amount": 0,
            "commission_amount": 597.5,
            "total_amount": 6572.5,
            "service_sub_bookings": [
              {
                "id": 385,
                "trader_user_id": 913,
                "trader_profile_id": 230,
                "customer_id": 913,
                "service_booking_id": 316,
                "wellbeing_trader_service_id": 109,
                "booking_date": "2019-09-30",
                "start_time": "21:00:00",
                "end_time": "22:00:00",
                "cost": 120,
                "created_at": "2019-09-26 20:16:54",
                "updated_at": "2019-09-26 20:16:54",
                "duration": 60,
                "wellbeing_trader_service": {
                  "id": 109,
                  "name": "Chırag Sharma"
                }
              },
              {
                "id": 386,
                "trader_user_id": 913,
                "trader_profile_id": 230,
                "customer_id": 913,
                "service_booking_id": 316,
                "wellbeing_trader_service_id": 243,
                "booking_date": "2019-09-30",
                "start_time": "22:00:00",
                "end_time": "22:30:00",
                "cost": 100,
                "created_at": "2019-09-26 20:16:54",
                "updated_at": "2019-09-26 20:16:54",
                "duration": 30,
                "wellbeing_trader_service": {
                  "id": 243,
                  "name": "Sea Spa Express"
                }
              },
              {
                "id": 387,
                "trader_user_id": 913,
                "trader_profile_id": 230,
                "customer_id": 913,
                "service_booking_id": 316,
                "wellbeing_trader_service_id": 244,
                "booking_date": "2019-09-30",
                "start_time": "22:30:00",
                "end_time": "23:00:00",
                "cost": 5755,
                "created_at": "2019-09-26 20:16:54",
                "updated_at": "2019-09-26 20:16:54",
                "duration": 30,
                "wellbeing_trader_service": {
                  "id": 244,
                  "name": "Anku"
                }
              }
            ],
            "trader_user_profile": {
              "id": 230,
              "user_id": 913,
              "service_type": "Spa and beauty"
            },
            "trader_user": {
              "id": 913,
              "business_name": "Orchid Day Spa &  Beauty",
              "business_location": "Place: London",
              "image": "http://localhost/upload_images/users/913/66954.jpeg",
              "business_state_id": "Victoria",
              "business_city_id": "New South Wales"
            },
            "valid_trader_rating": null
          }
        ]
     