export const MY_BOOKING =   [
  {
      "id": 1,
      "customer_id": 706,
      "trader_class_id": 16,
      "booking_type": "subscription-based",
      "quantity": 1,
      "status": "Accepted-Paid",
      "booking_date": "2020-01-29",
      "booking_time": "01:30:00",
      "booking_end_time": null,
      "booking_duration": null,
      "sub_total": 0,
      "service_fee": 0,
      "taxes_fees": 0,
      "total": 0,
      "commission_percentage": 0,
      "gst_percentage": 0,
      "stripe_payment_intent_id": null,
      "stripe_payment_intent_status": "succeeded",
      "stripe_transaction_fee": "0",
      "created_at": "2020-01-27 07:41:19",
      "updated_at": "2020-03-12 13:14:53",
      "subscription_unique_id": "7067138nWCoE",
      "cancellation_reason": null,
      "trader_user_id": 1024,
      "subscription_id": null,
      "deleted_at": null,
      "customer_name": "",
      "customer_phone": "",
      "promo_code_id": null,
      "discount_amount": 0,
      "category_name": "Wellbeing",
      "sub_category_name": "Fitness",
      "trader_class": {
          "id": 16,
          "trader_user_profile_id": 315,
          "wellbeing_fitness_type_id": 2,
          "type": "Weekly",
          "class_name": "arobica",
          "instructor_name": "Zain Farooq",
          "description": "new Testing Description",
          "room": "arobic room",
          "capacity": 60,
          "price": 10,
          "image": null,
          "is_active": 1,
          "created_at": "2020-01-24 21:05:42",
          "updated_at": "2020-01-24 21:58:04",
          "start_date": "01-11-2020",
          "end_date": "30-11-2020",
          "class_time": null,
          "deleted_at": null,
          "total_price": 11,
          "trader_ratings": []
      },
      "vendor": {
          "id": 1024,
          "name": "fitness test",
          "fname": "fitness",
          "lname": "test",
          "email": "fitness@gmail.com",
          "image": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg",
          "verification_code": "zEORtqYIpKgYJ3apQpVHbvtprWxELt",
          "status": 1,
          "_token": "",
          "seller_type": "fitness",
          "social_id": null,
          "login_type": "",
          "role_id": 0,
          "mobile_no": "7976764646",
          "mobile_no_verified": 1,
          "active_role_name": null,
          "location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
          "state": "",
          "city": "",
          "phonecode": "+61",
          "country": null,
          "latitude": null,
          "longitude": null,
          "pincode": "",
          "is_notification_active": 0,
          "is_survey_active": 0,
          "is_invites_active": 0,
          "is_newsletter_active": 0,
          "new_requested_email": null,
          "new_requested_email_status": 0,
          "email_updation_verification_code": null,
          "created_at": "2019-12-06 17:35:45",
          "updated_at": "2020-11-26 08:53:56",
          "avatar": null,
          "device_id": null,
          "device_model": null,
          "device_type": null,
          "os_version": null,
          "network_provider": null,
          "app_version_no": null,
          "business_name": "fitness vendor",
          "business_location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
          "business_state_id": "New South Wales",
          "business_city_id": "Port Macquarie",
          "business_pincode": "2444",
          "business_lat": "-31.429517899999997",
          "business_lng": "152.8961441",
          "business_suburb": null,
          "paypal_email": null,
          "stripe_customer_id": "",
          "braintree_id": null,
          "card_brand": null,
          "card_last_four": null,
          "payment_method_token": null,
          "trial_ends_at": null,
          "blocked": 0,
          "active": 1,
          "last_active": "2020-11-26 08:53:56",
          "profile_completed": 1,
          "braintree_nonce": "",
          "views": 2,
          "menu_skipped": 0,
          "image_thumbnail": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg"
      }
  }
]


    export const BOOKING_HISTORY =  [
            {
              "id": 1,
              "trader_user_profile_id": 233,
              "trader_user_id": 917,
              "customer_id": 482,
              "trader_class_id": null,
              "trader_class_schedule_id": null,
              "trader_class_package_id": 1,
              "name": "Basic",
              "phone_number": null,
              "sub_total": 154,
              "service_fee": 0,
              "taxes_fees": 0,
              "total": 154,
              "start_date": "2020-01-22",
              "end_date": {
                "date": "2020-02-25 00:00:00.000000",
                "timezone_type": 3,
                "timezone": "UTC"
              },
              "start_time": null,
              "end_time": null,
              "subscription_type": null,
              "status": "Accepted-Paid",
              "commission_percentage": 0,
              "gst_percentage": 0,
              "created_at": "2020-01-22 09:37:05",
              "updated_at": "2020-01-22 09:37:11",
              "stripe_payment_intent_id": null,
              "stripe_payment_intent_status": "succeeded",
              "start_from": null,
              "class_count": 25,
              "unique_id": "4829171EEDHj",
              "pid": 0,
              "deleted_at": null,
              "trader_user_profile": {
                "id": 233,
                "user_id": 917,
                "booking_cat_id": 3,
                "booking_sub_cat_id": 41,
                "service_type": "Health Club",
                "trader_service": {
                  "id": 41,
                  "name": "Fitness"
                },
                "user": {
                  "id": 917,
                  "business_name": "ByUBeMetro Body Health Fitness",
                  "business_location": "43A Queen Street Saint Marys Australia",
                  "image": "http://test.formee.co/upload_images/users/5e69ee8f999be.jpeg",
                  "image_thumbnail": "http://test.formee.co/upload_images/users/m/5e69ee8f999be.jpeg"
                }
              },
              "trader_class": null,
              "trader_class_schedule": null,
              "trader_class_package": {
                "id": 1,
                "trader_user_profile_id": 233,
                "trader_class_id": null,
                "name": "Basics",
                "detail": "Test for Pilates",
                "price": 154,
                "duration": "5-weeks-unlimited",
                "is_active": 1,
                "created_at": "2020-01-21 08:18:01",
                "updated_at": "2020-03-12 12:50:58",
                "class_count": 5,
                "quantity": 125,
                "available_from": "23-01-2020",
                "available_to": "29-01-2020",
                "total": 25,
                "deleted_at": null,
                "total_price": 169.4
              },
              "valid_trader_rating": {
                "id": 78,
                "trader_job_id": null,
                "rated_by": "customer",
                "trader_id": 917,
                "customer_id": 901,
                "title": "Review From Fitness Customer",
                "rating": 3,
                "status": 1,
                "rateable_id": 1,
                "rateable_type": "Modules\\WellBeing\\Models\\FitnessClassSubscription",
                "created_at": "2019-09-17 11:41:40",
                "updated_at": "2019-09-17 11:41:40",
                "review": "Bnjkbjknb"
              }
            },
            {
              "id": 3,
              "trader_user_profile_id": 315,
              "trader_user_id": 1024,
              "customer_id": 482,
              "trader_class_id": null,
              "trader_class_schedule_id": null,
              "trader_class_package_id": 3,
              "name": "Pilate Economy Package",
              "phone_number": null,
              "sub_total": 244,
              "service_fee": null,
              "taxes_fees": null,
              "total": 244,
              "start_date": "2020-01-22",
              "end_date": {
                "date": "2020-02-11 00:00:00.000000",
                "timezone_type": 3,
                "timezone": "UTC"
              },
              "start_time": null,
              "end_time": null,
              "subscription_type": null,
              "status": "Accepted-Paid",
              "commission_percentage": 10,
              "gst_percentage": 10,
              "created_at": "2020-01-22 14:39:38",
              "updated_at": "2020-01-22 14:39:42",
              "stripe_payment_intent_id": null,
              "stripe_payment_intent_status": "succeeded",
              "start_from": null,
              "class_count": 36,
              "unique_id": "48210243yAvbU",
              "pid": 0,
              "deleted_at": null,
              "trader_user_profile": {
                "id": 315,
                "user_id": 1024,
                "booking_cat_id": 3,
                "booking_sub_cat_id": 41,
                "service_type": null,
                "trader_service": {
                  "id": 41,
                  "name": "Fitness"
                },
                "user": {
                  "id": 1024,
                  "business_name": "fitness vendor",
                  "business_location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
                  "image": "http://test.formee.co/upload_images/users/1024/49526.jpg",
                  "image_thumbnail": "http://test.formee.co/upload_images/users/1024/49526.jpg"
                }
              },
              "trader_class": null,
              "trader_class_schedule": null,
              "trader_class_package": {
                "id": 3,
                "trader_user_profile_id": 315,
                "trader_class_id": null,
                "name": "Pilate Economy Package",
                "detail": "Djdjd hsjd ",
                "price": 244,
                "duration": "3-weeks-unlimited",
                "is_active": 1,
                "created_at": "2020-01-22 14:33:30",
                "updated_at": "2020-01-22 14:33:30",
                "class_count": 12,
                "quantity": 10,
                "available_from": "24-01-2020",
                "available_to": "14-02-2020",
                "total": 36,
                "deleted_at": null,
                "total_price": 268.4
              },
              "valid_trader_rating": {
                "id": 95,
                "trader_job_id": null,
                "rated_by": "customer",
                "trader_id": 917,
                "customer_id": 901,
                "title": "Review From Fitness Customer",
                "rating": 5,
                "status": 1,
                "rateable_id": 3,
                "rateable_type": "Modules\\WellBeing\\Models\\FitnessClassSubscription",
                "created_at": "2019-09-23 09:45:42",
                "updated_at": "2019-09-23 09:45:42",
                "review": "Good "
              }
            }
          ]
         
export const MEMBERSHIP_LISTING = [
      {
          "id": 1,
          "trader_user_profile_id": 315,
          "trader_user_id": 1024,
          "customer_id": 482,
          "trader_class_id": null,
          "trader_class_schedule_id": null,
          "trader_class_package_id": 1,
          "name": "Test 12345",
          "phone_number": null,
          "sub_total": 7.68,
          "service_fee": null,
          "taxes_fees": null,
          "total": 9.22,
          "start_date": "2020-11-19",
          "end_date": {
              "date": "2020-11-29 00:00:00.000000",
              "timezone_type": 3,
              "timezone": "Asia/Kolkata"
          },
          "start_time": null,
          "end_time": null,
          "subscription_type": null,
          "status": "Pending",
          "commission_percentage": 10,
          "gst_percentage": 10,
          "created_at": "2020-03-21 20:31:16",
          "updated_at": "2020-04-01 11:25:42",
          "stripe_payment_intent_id": null,
          "stripe_payment_intent_status": "succeeded",
          "start_from": null,
          "class_count": 0,
          "unique_id": null,
          "pid": 0,
          "deleted_at": null,
          "customer_name": "",
          "customer_phone": "",
          "ending_date": "2020-11-29",
          "package_id": 1,
          "package_name": "Test 123",
          "package_description": "Gngfnh",
          "package_price": 7.68,
          "package_duration": "6-weeks",
          "package_class_count": 2,
          "package_quantity": 1,
          "package_available_from": "2020-11-01 00:00:00",
          "package_available_to": "2020-12-31 00:00:00",
          "package_total": 150,
          "trader_user": {
              "id": 1024,
              "name": "fitness test",
              "fname": "fitness",
              "lname": "test",
              "email": "fitness@gmail.com",
              "image": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg",
              "verification_code": "zEORtqYIpKgYJ3apQpVHbvtprWxELt",
              "status": 1,
              "_token": "",
              "seller_type": "fitness",
              "social_id": null,
              "login_type": "",
              "role_id": 0,
              "mobile_no": "7976764646",
              "mobile_no_verified": 1,
              "active_role_name": null,
              "location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "state": "",
              "city": "",
              "phonecode": "+61",
              "country": null,
              "latitude": null,
              "longitude": null,
              "pincode": "",
              "is_notification_active": 0,
              "is_survey_active": 0,
              "is_invites_active": 0,
              "is_newsletter_active": 0,
              "new_requested_email": null,
              "new_requested_email_status": 0,
              "email_updation_verification_code": null,
              "created_at": "2019-12-06 17:35:45",
              "updated_at": "2020-11-26 08:53:56",
              "avatar": null,
              "device_id": null,
              "device_model": null,
              "device_type": null,
              "os_version": null,
              "network_provider": null,
              "app_version_no": null,
              "business_name": "fitness vendor",
              "business_location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "business_state_id": "New South Wales",
              "business_city_id": "Port Macquarie",
              "business_pincode": "2444",
              "business_lat": "-31.429517899999997",
              "business_lng": "152.8961441",
              "business_suburb": null,
              "paypal_email": null,
              "stripe_customer_id": "",
              "braintree_id": null,
              "card_brand": null,
              "card_last_four": null,
              "payment_method_token": null,
              "trial_ends_at": null,
              "blocked": 0,
              "active": 1,
              "last_active": "2020-11-26 08:53:56",
              "profile_completed": 1,
              "braintree_nonce": "",
              "views": 2,
              "menu_skipped": 0,
              "image_thumbnail": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg"
          }
      },
      {
          "id": 2,
          "trader_user_profile_id": 315,
          "trader_user_id": 1024,
          "customer_id": 482,
          "trader_class_id": null,
          "trader_class_schedule_id": null,
          "trader_class_package_id": 1,
          "name": "Test",
          "phone_number": null,
          "sub_total": 7.68,
          "service_fee": null,
          "taxes_fees": null,
          "total": 9.22,
          "start_date": "2020-11-19",
          "end_date": {
              "date": "2020-11-29 00:00:00.000000",
              "timezone_type": 3,
              "timezone": "Asia/Kolkata"
          },
          "start_time": null,
          "end_time": null,
          "subscription_type": null,
          "status": "Pending",
          "commission_percentage": 10,
          "gst_percentage": 10,
          "created_at": "2020-03-21 20:38:41",
          "updated_at": "2020-03-21 20:38:41",
          "stripe_payment_intent_id": null,
          "stripe_payment_intent_status": null,
          "start_from": null,
          "class_count": 0,
          "unique_id": null,
          "pid": 0,
          "deleted_at": null,
          "customer_name": "",
          "customer_phone": "",
          "ending_date": "2020-11-29",
          "package_id": 1,
          "package_name": "Test 123",
          "package_description": "Gngfnh",
          "package_price": 7.68,
          "package_duration": "6-weeks",
          "package_class_count": 2,
          "package_quantity": 1,
          "package_available_from": "2020-11-01 00:00:00",
          "package_available_to": "2020-12-31 00:00:00",
          "package_total": 150,
          "trader_user": {
              "id": 1024,
              "name": "fitness test",
              "fname": "fitness",
              "lname": "test",
              "email": "fitness@gmail.com",
              "image": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg",
              "verification_code": "zEORtqYIpKgYJ3apQpVHbvtprWxELt",
              "status": 1,
              "_token": "",
              "seller_type": "fitness",
              "social_id": null,
              "login_type": "",
              "role_id": 0,
              "mobile_no": "7976764646",
              "mobile_no_verified": 1,
              "active_role_name": null,
              "location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "state": "",
              "city": "",
              "phonecode": "+61",
              "country": null,
              "latitude": null,
              "longitude": null,
              "pincode": "",
              "is_notification_active": 0,
              "is_survey_active": 0,
              "is_invites_active": 0,
              "is_newsletter_active": 0,
              "new_requested_email": null,
              "new_requested_email_status": 0,
              "email_updation_verification_code": null,
              "created_at": "2019-12-06 17:35:45",
              "updated_at": "2020-11-26 08:53:56",
              "avatar": null,
              "device_id": null,
              "device_model": null,
              "device_type": null,
              "os_version": null,
              "network_provider": null,
              "app_version_no": null,
              "business_name": "fitness vendor",
              "business_location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "business_state_id": "New South Wales",
              "business_city_id": "Port Macquarie",
              "business_pincode": "2444",
              "business_lat": "-31.429517899999997",
              "business_lng": "152.8961441",
              "business_suburb": null,
              "paypal_email": null,
              "stripe_customer_id": "",
              "braintree_id": null,
              "card_brand": null,
              "card_last_four": null,
              "payment_method_token": null,
              "trial_ends_at": null,
              "blocked": 0,
              "active": 1,
              "last_active": "2020-11-26 08:53:56",
              "profile_completed": 1,
              "braintree_nonce": "",
              "views": 2,
              "menu_skipped": 0,
              "image_thumbnail": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg"
          }
      },
      {
          "id": 3,
          "trader_user_profile_id": 315,
          "trader_user_id": 1024,
          "customer_id": 482,
          "trader_class_id": null,
          "trader_class_schedule_id": null,
          "trader_class_package_id": 1,
          "name": "Test",
          "phone_number": null,
          "sub_total": 7.68,
          "service_fee": null,
          "taxes_fees": null,
          "total": 9.22,
          "start_date": "2020-11-19",
          "end_date": {
              "date": "2020-11-29 00:00:00.000000",
              "timezone_type": 3,
              "timezone": "Asia/Kolkata"
          },
          "start_time": null,
          "end_time": null,
          "subscription_type": null,
          "status": "Pending",
          "commission_percentage": 10,
          "gst_percentage": 10,
          "created_at": "2020-03-21 20:46:46",
          "updated_at": "2020-03-21 20:46:46",
          "stripe_payment_intent_id": null,
          "stripe_payment_intent_status": null,
          "start_from": null,
          "class_count": 0,
          "unique_id": null,
          "pid": 0,
          "deleted_at": null,
          "customer_name": "",
          "customer_phone": "",
          "ending_date": "2020-11-29",
          "package_id": 1,
          "package_name": "Test 123",
          "package_description": "Gngfnh",
          "package_price": 7.68,
          "package_duration": "6-weeks",
          "package_class_count": 2,
          "package_quantity": 1,
          "package_available_from": "2020-11-01 00:00:00",
          "package_available_to": "2020-12-31 00:00:00",
          "package_total": 150,
          "trader_user": {
              "id": 1024,
              "name": "fitness test",
              "fname": "fitness",
              "lname": "test",
              "email": "fitness@gmail.com",
              "image": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg",
              "verification_code": "zEORtqYIpKgYJ3apQpVHbvtprWxELt",
              "status": 1,
              "_token": "",
              "seller_type": "fitness",
              "social_id": null,
              "login_type": "",
              "role_id": 0,
              "mobile_no": "7976764646",
              "mobile_no_verified": 1,
              "active_role_name": null,
              "location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "state": "",
              "city": "",
              "phonecode": "+61",
              "country": null,
              "latitude": null,
              "longitude": null,
              "pincode": "",
              "is_notification_active": 0,
              "is_survey_active": 0,
              "is_invites_active": 0,
              "is_newsletter_active": 0,
              "new_requested_email": null,
              "new_requested_email_status": 0,
              "email_updation_verification_code": null,
              "created_at": "2019-12-06 17:35:45",
              "updated_at": "2020-11-26 08:53:56",
              "avatar": null,
              "device_id": null,
              "device_model": null,
              "device_type": null,
              "os_version": null,
              "network_provider": null,
              "app_version_no": null,
              "business_name": "fitness vendor",
              "business_location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "business_state_id": "New South Wales",
              "business_city_id": "Port Macquarie",
              "business_pincode": "2444",
              "business_lat": "-31.429517899999997",
              "business_lng": "152.8961441",
              "business_suburb": null,
              "paypal_email": null,
              "stripe_customer_id": "",
              "braintree_id": null,
              "card_brand": null,
              "card_last_four": null,
              "payment_method_token": null,
              "trial_ends_at": null,
              "blocked": 0,
              "active": 1,
              "last_active": "2020-11-26 08:53:56",
              "profile_completed": 1,
              "braintree_nonce": "",
              "views": 2,
              "menu_skipped": 0,
              "image_thumbnail": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg"
          }
      },
      {
          "id": 4,
          "trader_user_profile_id": 315,
          "trader_user_id": 1024,
          "customer_id": 482,
          "trader_class_id": null,
          "trader_class_schedule_id": null,
          "trader_class_package_id": 1,
          "name": "Test",
          "phone_number": null,
          "sub_total": 7.68,
          "service_fee": null,
          "taxes_fees": null,
          "total": 9.22,
          "start_date": "2020-11-19",
          "end_date": {
              "date": "2020-11-29 00:00:00.000000",
              "timezone_type": 3,
              "timezone": "Asia/Kolkata"
          },
          "start_time": null,
          "end_time": null,
          "subscription_type": null,
          "status": "Pending",
          "commission_percentage": 10,
          "gst_percentage": 10,
          "created_at": "2020-03-21 20:50:22",
          "updated_at": "2020-03-21 20:50:22",
          "stripe_payment_intent_id": null,
          "stripe_payment_intent_status": null,
          "start_from": null,
          "class_count": 0,
          "unique_id": null,
          "pid": 0,
          "deleted_at": null,
          "customer_name": "",
          "customer_phone": "",
          "ending_date": "2020-11-29",
          "package_id": 1,
          "package_name": "Test 123",
          "package_description": "Gngfnh",
          "package_price": 7.68,
          "package_duration": "6-weeks",
          "package_class_count": 2,
          "package_quantity": 1,
          "package_available_from": "2020-11-01 00:00:00",
          "package_available_to": "2020-12-31 00:00:00",
          "package_total": 150,
          "trader_user": {
              "id": 1024,
              "name": "fitness test",
              "fname": "fitness",
              "lname": "test",
              "email": "fitness@gmail.com",
              "image": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg",
              "verification_code": "zEORtqYIpKgYJ3apQpVHbvtprWxELt",
              "status": 1,
              "_token": "",
              "seller_type": "fitness",
              "social_id": null,
              "login_type": "",
              "role_id": 0,
              "mobile_no": "7976764646",
              "mobile_no_verified": 1,
              "active_role_name": null,
              "location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "state": "",
              "city": "",
              "phonecode": "+61",
              "country": null,
              "latitude": null,
              "longitude": null,
              "pincode": "",
              "is_notification_active": 0,
              "is_survey_active": 0,
              "is_invites_active": 0,
              "is_newsletter_active": 0,
              "new_requested_email": null,
              "new_requested_email_status": 0,
              "email_updation_verification_code": null,
              "created_at": "2019-12-06 17:35:45",
              "updated_at": "2020-11-26 08:53:56",
              "avatar": null,
              "device_id": null,
              "device_model": null,
              "device_type": null,
              "os_version": null,
              "network_provider": null,
              "app_version_no": null,
              "business_name": "fitness vendor",
              "business_location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "business_state_id": "New South Wales",
              "business_city_id": "Port Macquarie",
              "business_pincode": "2444",
              "business_lat": "-31.429517899999997",
              "business_lng": "152.8961441",
              "business_suburb": null,
              "paypal_email": null,
              "stripe_customer_id": "",
              "braintree_id": null,
              "card_brand": null,
              "card_last_four": null,
              "payment_method_token": null,
              "trial_ends_at": null,
              "blocked": 0,
              "active": 1,
              "last_active": "2020-11-26 08:53:56",
              "profile_completed": 1,
              "braintree_nonce": "",
              "views": 2,
              "menu_skipped": 0,
              "image_thumbnail": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg"
          }
      },
      {
          "id": 5,
          "trader_user_profile_id": 315,
          "trader_user_id": 1024,
          "customer_id": 482,
          "trader_class_id": null,
          "trader_class_schedule_id": null,
          "trader_class_package_id": 1,
          "name": "Test",
          "phone_number": null,
          "sub_total": 7.68,
          "service_fee": null,
          "taxes_fees": null,
          "total": 9.22,
          "start_date": "2020-11-20",
          "end_date": {
              "date": "2020-11-30 00:00:00.000000",
              "timezone_type": 3,
              "timezone": "Asia/Kolkata"
          },
          "start_time": null,
          "end_time": null,
          "subscription_type": null,
          "status": "Pending",
          "commission_percentage": 10,
          "gst_percentage": 10,
          "created_at": "2020-03-21 20:51:35",
          "updated_at": "2020-03-21 20:51:35",
          "stripe_payment_intent_id": null,
          "stripe_payment_intent_status": null,
          "start_from": null,
          "class_count": 0,
          "unique_id": null,
          "pid": 0,
          "deleted_at": null,
          "customer_name": "",
          "customer_phone": "",
          "ending_date": "2020-11-30",
          "package_id": 1,
          "package_name": "Test 123",
          "package_description": "Gngfnh",
          "package_price": 7.68,
          "package_duration": "6-weeks",
          "package_class_count": 2,
          "package_quantity": 1,
          "package_available_from": "2020-11-01 00:00:00",
          "package_available_to": "2020-12-31 00:00:00",
          "package_total": 150,
          "trader_user": {
              "id": 1024,
              "name": "fitness test",
              "fname": "fitness",
              "lname": "test",
              "email": "fitness@gmail.com",
              "image": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg",
              "verification_code": "zEORtqYIpKgYJ3apQpVHbvtprWxELt",
              "status": 1,
              "_token": "",
              "seller_type": "fitness",
              "social_id": null,
              "login_type": "",
              "role_id": 0,
              "mobile_no": "7976764646",
              "mobile_no_verified": 1,
              "active_role_name": null,
              "location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "state": "",
              "city": "",
              "phonecode": "+61",
              "country": null,
              "latitude": null,
              "longitude": null,
              "pincode": "",
              "is_notification_active": 0,
              "is_survey_active": 0,
              "is_invites_active": 0,
              "is_newsletter_active": 0,
              "new_requested_email": null,
              "new_requested_email_status": 0,
              "email_updation_verification_code": null,
              "created_at": "2019-12-06 17:35:45",
              "updated_at": "2020-11-26 08:53:56",
              "avatar": null,
              "device_id": null,
              "device_model": null,
              "device_type": null,
              "os_version": null,
              "network_provider": null,
              "app_version_no": null,
              "business_name": "fitness vendor",
              "business_location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "business_state_id": "New South Wales",
              "business_city_id": "Port Macquarie",
              "business_pincode": "2444",
              "business_lat": "-31.429517899999997",
              "business_lng": "152.8961441",
              "business_suburb": null,
              "paypal_email": null,
              "stripe_customer_id": "",
              "braintree_id": null,
              "card_brand": null,
              "card_last_four": null,
              "payment_method_token": null,
              "trial_ends_at": null,
              "blocked": 0,
              "active": 1,
              "last_active": "2020-11-26 08:53:56",
              "profile_completed": 1,
              "braintree_nonce": "",
              "views": 2,
              "menu_skipped": 0,
              "image_thumbnail": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg"
          }
      },
      {
          "id": 6,
          "trader_user_profile_id": 315,
          "trader_user_id": 1024,
          "customer_id": 482,
          "trader_class_id": null,
          "trader_class_schedule_id": null,
          "trader_class_package_id": 1,
          "name": "Test",
          "phone_number": null,
          "sub_total": 7.68,
          "service_fee": null,
          "taxes_fees": null,
          "total": 9.22,
          "start_date": "2020-11-20",
          "end_date": {
              "date": "2020-11-30 00:00:00.000000",
              "timezone_type": 3,
              "timezone": "Asia/Kolkata"
          },
          "start_time": null,
          "end_time": null,
          "subscription_type": null,
          "status": "Pending",
          "commission_percentage": 10,
          "gst_percentage": 10,
          "created_at": "2020-03-21 20:53:34",
          "updated_at": "2020-03-21 20:53:34",
          "stripe_payment_intent_id": null,
          "stripe_payment_intent_status": null,
          "start_from": null,
          "class_count": 0,
          "unique_id": null,
          "pid": 0,
          "deleted_at": null,
          "customer_name": "",
          "customer_phone": "",
          "ending_date": "2020-11-30",
          "package_id": 1,
          "package_name": "Test 123",
          "package_description": "Gngfnh",
          "package_price": 7.68,
          "package_duration": "6-weeks",
          "package_class_count": 2,
          "package_quantity": 1,
          "package_available_from": "2020-11-01 00:00:00",
          "package_available_to": "2020-12-31 00:00:00",
          "package_total": 150,
          "trader_user": {
              "id": 1024,
              "name": "fitness test",
              "fname": "fitness",
              "lname": "test",
              "email": "fitness@gmail.com",
              "image": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg",
              "verification_code": "zEORtqYIpKgYJ3apQpVHbvtprWxELt",
              "status": 1,
              "_token": "",
              "seller_type": "fitness",
              "social_id": null,
              "login_type": "",
              "role_id": 0,
              "mobile_no": "7976764646",
              "mobile_no_verified": 1,
              "active_role_name": null,
              "location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "state": "",
              "city": "",
              "phonecode": "+61",
              "country": null,
              "latitude": null,
              "longitude": null,
              "pincode": "",
              "is_notification_active": 0,
              "is_survey_active": 0,
              "is_invites_active": 0,
              "is_newsletter_active": 0,
              "new_requested_email": null,
              "new_requested_email_status": 0,
              "email_updation_verification_code": null,
              "created_at": "2019-12-06 17:35:45",
              "updated_at": "2020-11-26 08:53:56",
              "avatar": null,
              "device_id": null,
              "device_model": null,
              "device_type": null,
              "os_version": null,
              "network_provider": null,
              "app_version_no": null,
              "business_name": "fitness vendor",
              "business_location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "business_state_id": "New South Wales",
              "business_city_id": "Port Macquarie",
              "business_pincode": "2444",
              "business_lat": "-31.429517899999997",
              "business_lng": "152.8961441",
              "business_suburb": null,
              "paypal_email": null,
              "stripe_customer_id": "",
              "braintree_id": null,
              "card_brand": null,
              "card_last_four": null,
              "payment_method_token": null,
              "trial_ends_at": null,
              "blocked": 0,
              "active": 1,
              "last_active": "2020-11-26 08:53:56",
              "profile_completed": 1,
              "braintree_nonce": "",
              "views": 2,
              "menu_skipped": 0,
              "image_thumbnail": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg"
          }
      },
      {
          "id": 7,
          "trader_user_profile_id": 315,
          "trader_user_id": 1024,
          "customer_id": 482,
          "trader_class_id": null,
          "trader_class_schedule_id": null,
          "trader_class_package_id": 1,
          "name": "Test",
          "phone_number": null,
          "sub_total": 7.68,
          "service_fee": null,
          "taxes_fees": null,
          "total": 9.22,
          "start_date": "2020-11-23",
          "end_date": {
              "date": "2020-11-26 00:00:00.000000",
              "timezone_type": 3,
              "timezone": "Asia/Kolkata"
          },
          "start_time": null,
          "end_time": null,
          "subscription_type": null,
          "status": "Pending",
          "commission_percentage": 10,
          "gst_percentage": 10,
          "created_at": "2020-03-21 20:55:12",
          "updated_at": "2020-03-21 20:55:12",
          "stripe_payment_intent_id": null,
          "stripe_payment_intent_status": null,
          "start_from": null,
          "class_count": 0,
          "unique_id": null,
          "pid": 0,
          "deleted_at": null,
          "customer_name": "",
          "customer_phone": "",
          "ending_date": "2020-11-26",
          "package_id": 1,
          "package_name": "Test 123",
          "package_description": "Gngfnh",
          "package_price": 7.68,
          "package_duration": "6-weeks",
          "package_class_count": 2,
          "package_quantity": 1,
          "package_available_from": "2020-11-01 00:00:00",
          "package_available_to": "2020-12-31 00:00:00",
          "package_total": 150,
          "trader_user": {
              "id": 1024,
              "name": "fitness test",
              "fname": "fitness",
              "lname": "test",
              "email": "fitness@gmail.com",
              "image": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg",
              "verification_code": "zEORtqYIpKgYJ3apQpVHbvtprWxELt",
              "status": 1,
              "_token": "",
              "seller_type": "fitness",
              "social_id": null,
              "login_type": "",
              "role_id": 0,
              "mobile_no": "7976764646",
              "mobile_no_verified": 1,
              "active_role_name": null,
              "location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "state": "",
              "city": "",
              "phonecode": "+61",
              "country": null,
              "latitude": null,
              "longitude": null,
              "pincode": "",
              "is_notification_active": 0,
              "is_survey_active": 0,
              "is_invites_active": 0,
              "is_newsletter_active": 0,
              "new_requested_email": null,
              "new_requested_email_status": 0,
              "email_updation_verification_code": null,
              "created_at": "2019-12-06 17:35:45",
              "updated_at": "2020-11-26 08:53:56",
              "avatar": null,
              "device_id": null,
              "device_model": null,
              "device_type": null,
              "os_version": null,
              "network_provider": null,
              "app_version_no": null,
              "business_name": "fitness vendor",
              "business_location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "business_state_id": "New South Wales",
              "business_city_id": "Port Macquarie",
              "business_pincode": "2444",
              "business_lat": "-31.429517899999997",
              "business_lng": "152.8961441",
              "business_suburb": null,
              "paypal_email": null,
              "stripe_customer_id": "",
              "braintree_id": null,
              "card_brand": null,
              "card_last_four": null,
              "payment_method_token": null,
              "trial_ends_at": null,
              "blocked": 0,
              "active": 1,
              "last_active": "2020-11-26 08:53:56",
              "profile_completed": 1,
              "braintree_nonce": "",
              "views": 2,
              "menu_skipped": 0,
              "image_thumbnail": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg"
          }
      },
      {
          "id": 8,
          "trader_user_profile_id": 315,
          "trader_user_id": 1024,
          "customer_id": 482,
          "trader_class_id": null,
          "trader_class_schedule_id": null,
          "trader_class_package_id": 1,
          "name": "Test",
          "phone_number": null,
          "sub_total": 7.68,
          "service_fee": null,
          "taxes_fees": null,
          "total": 9.22,
          "start_date": "2020-11-23",
          "end_date": {
              "date": "2020-11-26 00:00:00.000000",
              "timezone_type": 3,
              "timezone": "Asia/Kolkata"
          },
          "start_time": null,
          "end_time": null,
          "subscription_type": null,
          "status": "Pending",
          "commission_percentage": 10,
          "gst_percentage": 10,
          "created_at": "2020-03-21 20:56:44",
          "updated_at": "2020-03-21 20:56:44",
          "stripe_payment_intent_id": null,
          "stripe_payment_intent_status": null,
          "start_from": null,
          "class_count": 0,
          "unique_id": null,
          "pid": 0,
          "deleted_at": null,
          "customer_name": "",
          "customer_phone": "",
          "ending_date": "2020-11-26",
          "package_id": 1,
          "package_name": "Test 123",
          "package_description": "Gngfnh",
          "package_price": 7.68,
          "package_duration": "6-weeks",
          "package_class_count": 2,
          "package_quantity": 1,
          "package_available_from": "2020-11-01 00:00:00",
          "package_available_to": "2020-12-31 00:00:00",
          "package_total": 150,
          "trader_user": {
              "id": 1024,
              "name": "fitness test",
              "fname": "fitness",
              "lname": "test",
              "email": "fitness@gmail.com",
              "image": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg",
              "verification_code": "zEORtqYIpKgYJ3apQpVHbvtprWxELt",
              "status": 1,
              "_token": "",
              "seller_type": "fitness",
              "social_id": null,
              "login_type": "",
              "role_id": 0,
              "mobile_no": "7976764646",
              "mobile_no_verified": 1,
              "active_role_name": null,
              "location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "state": "",
              "city": "",
              "phonecode": "+61",
              "country": null,
              "latitude": null,
              "longitude": null,
              "pincode": "",
              "is_notification_active": 0,
              "is_survey_active": 0,
              "is_invites_active": 0,
              "is_newsletter_active": 0,
              "new_requested_email": null,
              "new_requested_email_status": 0,
              "email_updation_verification_code": null,
              "created_at": "2019-12-06 17:35:45",
              "updated_at": "2020-11-26 08:53:56",
              "avatar": null,
              "device_id": null,
              "device_model": null,
              "device_type": null,
              "os_version": null,
              "network_provider": null,
              "app_version_no": null,
              "business_name": "fitness vendor",
              "business_location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "business_state_id": "New South Wales",
              "business_city_id": "Port Macquarie",
              "business_pincode": "2444",
              "business_lat": "-31.429517899999997",
              "business_lng": "152.8961441",
              "business_suburb": null,
              "paypal_email": null,
              "stripe_customer_id": "",
              "braintree_id": null,
              "card_brand": null,
              "card_last_four": null,
              "payment_method_token": null,
              "trial_ends_at": null,
              "blocked": 0,
              "active": 1,
              "last_active": "2020-11-26 08:53:56",
              "profile_completed": 1,
              "braintree_nonce": "",
              "views": 2,
              "menu_skipped": 0,
              "image_thumbnail": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg"
          }
      },
      {
          "id": 9,
          "trader_user_profile_id": 315,
          "trader_user_id": 1024,
          "customer_id": 482,
          "trader_class_id": null,
          "trader_class_schedule_id": null,
          "trader_class_package_id": 1,
          "name": "Test",
          "phone_number": null,
          "sub_total": 7.68,
          "service_fee": null,
          "taxes_fees": null,
          "total": 9.22,
          "start_date": "2020-11-23",
          "end_date": {
              "date": "2020-11-26 00:00:00.000000",
              "timezone_type": 3,
              "timezone": "Asia/Kolkata"
          },
          "start_time": null,
          "end_time": null,
          "subscription_type": null,
          "status": "Pending",
          "commission_percentage": 10,
          "gst_percentage": 10,
          "created_at": "2020-03-21 21:11:20",
          "updated_at": "2020-03-21 21:11:20",
          "stripe_payment_intent_id": null,
          "stripe_payment_intent_status": null,
          "start_from": null,
          "class_count": 0,
          "unique_id": null,
          "pid": 0,
          "deleted_at": null,
          "customer_name": "",
          "customer_phone": "",
          "ending_date": "2020-11-26",
          "package_id": 1,
          "package_name": "Test 123",
          "package_description": "Gngfnh",
          "package_price": 7.68,
          "package_duration": "6-weeks",
          "package_class_count": 2,
          "package_quantity": 1,
          "package_available_from": "2020-11-01 00:00:00",
          "package_available_to": "2020-12-31 00:00:00",
          "package_total": 150,
          "trader_user": {
              "id": 1024,
              "name": "fitness test",
              "fname": "fitness",
              "lname": "test",
              "email": "fitness@gmail.com",
              "image": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg",
              "verification_code": "zEORtqYIpKgYJ3apQpVHbvtprWxELt",
              "status": 1,
              "_token": "",
              "seller_type": "fitness",
              "social_id": null,
              "login_type": "",
              "role_id": 0,
              "mobile_no": "7976764646",
              "mobile_no_verified": 1,
              "active_role_name": null,
              "location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "state": "",
              "city": "",
              "phonecode": "+61",
              "country": null,
              "latitude": null,
              "longitude": null,
              "pincode": "",
              "is_notification_active": 0,
              "is_survey_active": 0,
              "is_invites_active": 0,
              "is_newsletter_active": 0,
              "new_requested_email": null,
              "new_requested_email_status": 0,
              "email_updation_verification_code": null,
              "created_at": "2019-12-06 17:35:45",
              "updated_at": "2020-11-26 08:53:56",
              "avatar": null,
              "device_id": null,
              "device_model": null,
              "device_type": null,
              "os_version": null,
              "network_provider": null,
              "app_version_no": null,
              "business_name": "fitness vendor",
              "business_location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "business_state_id": "New South Wales",
              "business_city_id": "Port Macquarie",
              "business_pincode": "2444",
              "business_lat": "-31.429517899999997",
              "business_lng": "152.8961441",
              "business_suburb": null,
              "paypal_email": null,
              "stripe_customer_id": "",
              "braintree_id": null,
              "card_brand": null,
              "card_last_four": null,
              "payment_method_token": null,
              "trial_ends_at": null,
              "blocked": 0,
              "active": 1,
              "last_active": "2020-11-26 08:53:56",
              "profile_completed": 1,
              "braintree_nonce": "",
              "views": 2,
              "menu_skipped": 0,
              "image_thumbnail": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg"
          }
      },
      {
          "id": 10,
          "trader_user_profile_id": 315,
          "trader_user_id": 1024,
          "customer_id": 482,
          "trader_class_id": null,
          "trader_class_schedule_id": null,
          "trader_class_package_id": 1,
          "name": "Test",
          "phone_number": null,
          "sub_total": 7.68,
          "service_fee": null,
          "taxes_fees": null,
          "total": 9.22,
          "start_date": "2020-11-23",
          "end_date": {
              "date": "2020-11-26 00:00:00.000000",
              "timezone_type": 3,
              "timezone": "Asia/Kolkata"
          },
          "start_time": null,
          "end_time": null,
          "subscription_type": null,
          "status": "Pending",
          "commission_percentage": 10,
          "gst_percentage": 10,
          "created_at": "2020-03-21 21:17:15",
          "updated_at": "2020-03-21 21:17:15",
          "stripe_payment_intent_id": null,
          "stripe_payment_intent_status": null,
          "start_from": null,
          "class_count": 0,
          "unique_id": null,
          "pid": 0,
          "deleted_at": null,
          "customer_name": "",
          "customer_phone": "",
          "ending_date": "2020-11-26",
          "package_id": 1,
          "package_name": "Test 123",
          "package_description": "Gngfnh",
          "package_price": 7.68,
          "package_duration": "6-weeks",
          "package_class_count": 2,
          "package_quantity": 1,
          "package_available_from": "2020-11-01 00:00:00",
          "package_available_to": "2020-12-31 00:00:00",
          "package_total": 150,
          "trader_user": {
              "id": 1024,
              "name": "fitness test",
              "fname": "fitness",
              "lname": "test",
              "email": "fitness@gmail.com",
              "image": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg",
              "verification_code": "zEORtqYIpKgYJ3apQpVHbvtprWxELt",
              "status": 1,
              "_token": "",
              "seller_type": "fitness",
              "social_id": null,
              "login_type": "",
              "role_id": 0,
              "mobile_no": "7976764646",
              "mobile_no_verified": 1,
              "active_role_name": null,
              "location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "state": "",
              "city": "",
              "phonecode": "+61",
              "country": null,
              "latitude": null,
              "longitude": null,
              "pincode": "",
              "is_notification_active": 0,
              "is_survey_active": 0,
              "is_invites_active": 0,
              "is_newsletter_active": 0,
              "new_requested_email": null,
              "new_requested_email_status": 0,
              "email_updation_verification_code": null,
              "created_at": "2019-12-06 17:35:45",
              "updated_at": "2020-11-26 08:53:56",
              "avatar": null,
              "device_id": null,
              "device_model": null,
              "device_type": null,
              "os_version": null,
              "network_provider": null,
              "app_version_no": null,
              "business_name": "fitness vendor",
              "business_location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "business_state_id": "New South Wales",
              "business_city_id": "Port Macquarie",
              "business_pincode": "2444",
              "business_lat": "-31.429517899999997",
              "business_lng": "152.8961441",
              "business_suburb": null,
              "paypal_email": null,
              "stripe_customer_id": "",
              "braintree_id": null,
              "card_brand": null,
              "card_last_four": null,
              "payment_method_token": null,
              "trial_ends_at": null,
              "blocked": 0,
              "active": 1,
              "last_active": "2020-11-26 08:53:56",
              "profile_completed": 1,
              "braintree_nonce": "",
              "views": 2,
              "menu_skipped": 0,
              "image_thumbnail": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg"
          }
      },
      {
          "id": 11,
          "trader_user_profile_id": 315,
          "trader_user_id": 1024,
          "customer_id": 482,
          "trader_class_id": null,
          "trader_class_schedule_id": null,
          "trader_class_package_id": 1,
          "name": "Test",
          "phone_number": null,
          "sub_total": 7.68,
          "service_fee": null,
          "taxes_fees": null,
          "total": 9.22,
          "start_date": "2020-11-23",
          "end_date": {
              "date": "2020-11-26 00:00:00.000000",
              "timezone_type": 3,
              "timezone": "Asia/Kolkata"
          },
          "start_time": null,
          "end_time": null,
          "subscription_type": null,
          "status": "Pending",
          "commission_percentage": 10,
          "gst_percentage": 10,
          "created_at": "2020-03-23 11:36:40",
          "updated_at": "2020-03-23 11:36:40",
          "stripe_payment_intent_id": null,
          "stripe_payment_intent_status": null,
          "start_from": null,
          "class_count": 0,
          "unique_id": null,
          "pid": 0,
          "deleted_at": null,
          "customer_name": "",
          "customer_phone": "",
          "ending_date": "2020-11-26",
          "package_id": 1,
          "package_name": "Test 123",
          "package_description": "Gngfnh",
          "package_price": 7.68,
          "package_duration": "6-weeks",
          "package_class_count": 2,
          "package_quantity": 1,
          "package_available_from": "2020-11-01 00:00:00",
          "package_available_to": "2020-12-31 00:00:00",
          "package_total": 150,
          "trader_user": {
              "id": 1024,
              "name": "fitness test",
              "fname": "fitness",
              "lname": "test",
              "email": "fitness@gmail.com",
              "image": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg",
              "verification_code": "zEORtqYIpKgYJ3apQpVHbvtprWxELt",
              "status": 1,
              "_token": "",
              "seller_type": "fitness",
              "social_id": null,
              "login_type": "",
              "role_id": 0,
              "mobile_no": "7976764646",
              "mobile_no_verified": 1,
              "active_role_name": null,
              "location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "state": "",
              "city": "",
              "phonecode": "+61",
              "country": null,
              "latitude": null,
              "longitude": null,
              "pincode": "",
              "is_notification_active": 0,
              "is_survey_active": 0,
              "is_invites_active": 0,
              "is_newsletter_active": 0,
              "new_requested_email": null,
              "new_requested_email_status": 0,
              "email_updation_verification_code": null,
              "created_at": "2019-12-06 17:35:45",
              "updated_at": "2020-11-26 08:53:56",
              "avatar": null,
              "device_id": null,
              "device_model": null,
              "device_type": null,
              "os_version": null,
              "network_provider": null,
              "app_version_no": null,
              "business_name": "fitness vendor",
              "business_location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "business_state_id": "New South Wales",
              "business_city_id": "Port Macquarie",
              "business_pincode": "2444",
              "business_lat": "-31.429517899999997",
              "business_lng": "152.8961441",
              "business_suburb": null,
              "paypal_email": null,
              "stripe_customer_id": "",
              "braintree_id": null,
              "card_brand": null,
              "card_last_four": null,
              "payment_method_token": null,
              "trial_ends_at": null,
              "blocked": 0,
              "active": 1,
              "last_active": "2020-11-26 08:53:56",
              "profile_completed": 1,
              "braintree_nonce": "",
              "views": 2,
              "menu_skipped": 0,
              "image_thumbnail": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg"
          }
      },
      {
          "id": 12,
          "trader_user_profile_id": 315,
          "trader_user_id": 1024,
          "customer_id": 482,
          "trader_class_id": null,
          "trader_class_schedule_id": null,
          "trader_class_package_id": 1,
          "name": "Test",
          "phone_number": null,
          "sub_total": 7.68,
          "service_fee": null,
          "taxes_fees": null,
          "total": 9.22,
          "start_date": "2020-11-23",
          "end_date": {
              "date": "2020-11-26 00:00:00.000000",
              "timezone_type": 3,
              "timezone": "Asia/Kolkata"
          },
          "start_time": null,
          "end_time": null,
          "subscription_type": null,
          "status": "Pending",
          "commission_percentage": 10,
          "gst_percentage": 10,
          "created_at": "2020-03-23 12:57:09",
          "updated_at": "2020-03-23 12:57:09",
          "stripe_payment_intent_id": null,
          "stripe_payment_intent_status": null,
          "start_from": null,
          "class_count": 0,
          "unique_id": null,
          "pid": 0,
          "deleted_at": null,
          "customer_name": "",
          "customer_phone": "",
          "ending_date": "2020-11-26",
          "package_id": 1,
          "package_name": "Test 123",
          "package_description": "Gngfnh",
          "package_price": 7.68,
          "package_duration": "6-weeks",
          "package_class_count": 2,
          "package_quantity": 1,
          "package_available_from": "2020-11-01 00:00:00",
          "package_available_to": "2020-12-31 00:00:00",
          "package_total": 150,
          "trader_user": {
              "id": 1024,
              "name": "fitness test",
              "fname": "fitness",
              "lname": "test",
              "email": "fitness@gmail.com",
              "image": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg",
              "verification_code": "zEORtqYIpKgYJ3apQpVHbvtprWxELt",
              "status": 1,
              "_token": "",
              "seller_type": "fitness",
              "social_id": null,
              "login_type": "",
              "role_id": 0,
              "mobile_no": "7976764646",
              "mobile_no_verified": 1,
              "active_role_name": null,
              "location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "state": "",
              "city": "",
              "phonecode": "+61",
              "country": null,
              "latitude": null,
              "longitude": null,
              "pincode": "",
              "is_notification_active": 0,
              "is_survey_active": 0,
              "is_invites_active": 0,
              "is_newsletter_active": 0,
              "new_requested_email": null,
              "new_requested_email_status": 0,
              "email_updation_verification_code": null,
              "created_at": "2019-12-06 17:35:45",
              "updated_at": "2020-11-26 08:53:56",
              "avatar": null,
              "device_id": null,
              "device_model": null,
              "device_type": null,
              "os_version": null,
              "network_provider": null,
              "app_version_no": null,
              "business_name": "fitness vendor",
              "business_location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "business_state_id": "New South Wales",
              "business_city_id": "Port Macquarie",
              "business_pincode": "2444",
              "business_lat": "-31.429517899999997",
              "business_lng": "152.8961441",
              "business_suburb": null,
              "paypal_email": null,
              "stripe_customer_id": "",
              "braintree_id": null,
              "card_brand": null,
              "card_last_four": null,
              "payment_method_token": null,
              "trial_ends_at": null,
              "blocked": 0,
              "active": 1,
              "last_active": "2020-11-26 08:53:56",
              "profile_completed": 1,
              "braintree_nonce": "",
              "views": 2,
              "menu_skipped": 0,
              "image_thumbnail": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg"
          }
      },
      {
          "id": 13,
          "trader_user_profile_id": 315,
          "trader_user_id": 1024,
          "customer_id": 482,
          "trader_class_id": null,
          "trader_class_schedule_id": null,
          "trader_class_package_id": 1,
          "name": "Test",
          "phone_number": null,
          "sub_total": 7.68,
          "service_fee": null,
          "taxes_fees": null,
          "total": 9.22,
          "start_date": "2020-11-23",
          "end_date": {
              "date": "2020-11-26 00:00:00.000000",
              "timezone_type": 3,
              "timezone": "Asia/Kolkata"
          },
          "start_time": null,
          "end_time": null,
          "subscription_type": null,
          "status": "Pending",
          "commission_percentage": 10,
          "gst_percentage": 10,
          "created_at": "2020-03-23 13:02:56",
          "updated_at": "2020-03-23 13:02:56",
          "stripe_payment_intent_id": null,
          "stripe_payment_intent_status": null,
          "start_from": null,
          "class_count": 0,
          "unique_id": null,
          "pid": 0,
          "deleted_at": null,
          "customer_name": "",
          "customer_phone": "",
          "ending_date": "2020-11-26",
          "package_id": 1,
          "package_name": "Test 123",
          "package_description": "Gngfnh",
          "package_price": 7.68,
          "package_duration": "6-weeks",
          "package_class_count": 2,
          "package_quantity": 1,
          "package_available_from": "2020-11-01 00:00:00",
          "package_available_to": "2020-12-31 00:00:00",
          "package_total": 150,
          "trader_user": {
              "id": 1024,
              "name": "fitness test",
              "fname": "fitness",
              "lname": "test",
              "email": "fitness@gmail.com",
              "image": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg",
              "verification_code": "zEORtqYIpKgYJ3apQpVHbvtprWxELt",
              "status": 1,
              "_token": "",
              "seller_type": "fitness",
              "social_id": null,
              "login_type": "",
              "role_id": 0,
              "mobile_no": "7976764646",
              "mobile_no_verified": 1,
              "active_role_name": null,
              "location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "state": "",
              "city": "",
              "phonecode": "+61",
              "country": null,
              "latitude": null,
              "longitude": null,
              "pincode": "",
              "is_notification_active": 0,
              "is_survey_active": 0,
              "is_invites_active": 0,
              "is_newsletter_active": 0,
              "new_requested_email": null,
              "new_requested_email_status": 0,
              "email_updation_verification_code": null,
              "created_at": "2019-12-06 17:35:45",
              "updated_at": "2020-11-26 08:53:56",
              "avatar": null,
              "device_id": null,
              "device_model": null,
              "device_type": null,
              "os_version": null,
              "network_provider": null,
              "app_version_no": null,
              "business_name": "fitness vendor",
              "business_location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "business_state_id": "New South Wales",
              "business_city_id": "Port Macquarie",
              "business_pincode": "2444",
              "business_lat": "-31.429517899999997",
              "business_lng": "152.8961441",
              "business_suburb": null,
              "paypal_email": null,
              "stripe_customer_id": "",
              "braintree_id": null,
              "card_brand": null,
              "card_last_four": null,
              "payment_method_token": null,
              "trial_ends_at": null,
              "blocked": 0,
              "active": 1,
              "last_active": "2020-11-26 08:53:56",
              "profile_completed": 1,
              "braintree_nonce": "",
              "views": 2,
              "menu_skipped": 0,
              "image_thumbnail": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg"
          }
      },
      {
          "id": 14,
          "trader_user_profile_id": 315,
          "trader_user_id": 1024,
          "customer_id": 482,
          "trader_class_id": null,
          "trader_class_schedule_id": null,
          "trader_class_package_id": 1,
          "name": "Test",
          "phone_number": null,
          "sub_total": 7.68,
          "service_fee": null,
          "taxes_fees": null,
          "total": 9.22,
          "start_date": "2020-11-23",
          "end_date": {
              "date": "2020-11-26 00:00:00.000000",
              "timezone_type": 3,
              "timezone": "Asia/Kolkata"
          },
          "start_time": null,
          "end_time": null,
          "subscription_type": null,
          "status": "Pending",
          "commission_percentage": 10,
          "gst_percentage": 10,
          "created_at": "2020-03-23 14:08:57",
          "updated_at": "2020-03-23 14:08:57",
          "stripe_payment_intent_id": null,
          "stripe_payment_intent_status": null,
          "start_from": null,
          "class_count": 0,
          "unique_id": null,
          "pid": 0,
          "deleted_at": null,
          "customer_name": "",
          "customer_phone": "",
          "ending_date": "2020-11-26",
          "package_id": 1,
          "package_name": "Test 123",
          "package_description": "Gngfnh",
          "package_price": 7.68,
          "package_duration": "6-weeks",
          "package_class_count": 2,
          "package_quantity": 1,
          "package_available_from": "2020-11-01 00:00:00",
          "package_available_to": "2020-12-31 00:00:00",
          "package_total": 150,
          "trader_user": {
              "id": 1024,
              "name": "fitness test",
              "fname": "fitness",
              "lname": "test",
              "email": "fitness@gmail.com",
              "image": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg",
              "verification_code": "zEORtqYIpKgYJ3apQpVHbvtprWxELt",
              "status": 1,
              "_token": "",
              "seller_type": "fitness",
              "social_id": null,
              "login_type": "",
              "role_id": 0,
              "mobile_no": "7976764646",
              "mobile_no_verified": 1,
              "active_role_name": null,
              "location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "state": "",
              "city": "",
              "phonecode": "+61",
              "country": null,
              "latitude": null,
              "longitude": null,
              "pincode": "",
              "is_notification_active": 0,
              "is_survey_active": 0,
              "is_invites_active": 0,
              "is_newsletter_active": 0,
              "new_requested_email": null,
              "new_requested_email_status": 0,
              "email_updation_verification_code": null,
              "created_at": "2019-12-06 17:35:45",
              "updated_at": "2020-11-26 08:53:56",
              "avatar": null,
              "device_id": null,
              "device_model": null,
              "device_type": null,
              "os_version": null,
              "network_provider": null,
              "app_version_no": null,
              "business_name": "fitness vendor",
              "business_location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "business_state_id": "New South Wales",
              "business_city_id": "Port Macquarie",
              "business_pincode": "2444",
              "business_lat": "-31.429517899999997",
              "business_lng": "152.8961441",
              "business_suburb": null,
              "paypal_email": null,
              "stripe_customer_id": "",
              "braintree_id": null,
              "card_brand": null,
              "card_last_four": null,
              "payment_method_token": null,
              "trial_ends_at": null,
              "blocked": 0,
              "active": 1,
              "last_active": "2020-11-26 08:53:56",
              "profile_completed": 1,
              "braintree_nonce": "",
              "views": 2,
              "menu_skipped": 0,
              "image_thumbnail": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg"
          }
      },
      {
          "id": 15,
          "trader_user_profile_id": 233,
          "trader_user_id": 917,
          "customer_id": 482,
          "trader_class_id": 1,
          "trader_class_schedule_id": 1,
          "trader_class_package_id": 2,
          "name": "Test",
          "phone_number": null,
          "sub_total": 10,
          "service_fee": null,
          "taxes_fees": null,
          "total": 12,
          "start_date": "2020-11-27",
          "end_date": {
              "date": "2020-11-30 00:00:00.000000",
              "timezone_type": 3,
              "timezone": "Asia/Kolkata"
          },
          "start_time": null,
          "end_time": null,
          "subscription_type": null,
          "status": "Accepted-Paid",
          "commission_percentage": 10,
          "gst_percentage": 10,
          "created_at": "2020-03-24 14:46:25",
          "updated_at": "2020-04-01 15:21:19",
          "stripe_payment_intent_id": null,
          "stripe_payment_intent_status": "succeeded",
          "start_from": null,
          "class_count": 0,
          "unique_id": null,
          "pid": 0,
          "deleted_at": null,
          "customer_name": "",
          "customer_phone": "",
          "ending_date": "2020-11-30",
          "package_id": 2,
          "package_name": "Testaaaa",
          "package_description": "Test details",
          "package_price": 10,
          "package_duration": "3",
          "package_class_count": 4,
          "package_quantity": 1,
          "package_available_from": "2020-03-24 12:57:29",
          "package_available_to": "2021-03-24 12:57:29",
          "package_total": 12,
          "trader_user": {
              "id": 917,
              "name": "Rajit Rana",
              "fname": "Rajit",
              "lname": "Rana",
              "email": "fitness@example.com",
              "image": "http://10.10.1.8/formee/upload_images/users/917/50410.jpg",
              "verification_code": "VwkLCBYYT5pIEobeEi7Fi7SlXk36Bv",
              "status": 1,
              "_token": "",
              "seller_type": "fitness",
              "social_id": null,
              "login_type": "",
              "role_id": 0,
              "mobile_no": "917698789912",
              "mobile_no_verified": 0,
              "active_role_name": null,
              "location": "1 Apple Park Way, Cupertino, CA, USA",
              "state": "",
              "city": "",
              "phonecode": "+61",
              "country": null,
              "latitude": "-37.814192",
              "longitude": "150.963351",
              "pincode": "",
              "is_notification_active": 0,
              "is_survey_active": 0,
              "is_invites_active": 0,
              "is_newsletter_active": 0,
              "new_requested_email": null,
              "new_requested_email_status": 0,
              "email_updation_verification_code": null,
              "created_at": "2019-08-12 14:34:15",
              "updated_at": "2020-11-26 11:43:01",
              "avatar": null,
              "device_id": null,
              "device_model": null,
              "device_type": null,
              "os_version": null,
              "network_provider": null,
              "app_version_no": null,
              "business_name": "Formee Fitness Vendor",
              "business_location": "1 Apple Park Way, Cupertino, CA, USA",
              "business_state_id": "Sydney Olympic Park",
              "business_city_id": "New South Wales",
              "business_pincode": "2127",
              "business_lat": "-33.84722079999999",
              "business_lng": "151.0726267",
              "business_suburb": null,
              "paypal_email": null,
              "stripe_customer_id": "",
              "braintree_id": null,
              "card_brand": null,
              "card_last_four": null,
              "payment_method_token": null,
              "trial_ends_at": null,
              "blocked": 0,
              "active": 1,
              "last_active": "2020-11-26 11:43:01",
              "profile_completed": 1,
              "braintree_nonce": "",
              "views": 634,
              "menu_skipped": 0,
              "image_thumbnail": "http://10.10.1.8/formee/upload_images/users/917/50410.jpg"
          }
      },
      {
          "id": 16,
          "trader_user_profile_id": 315,
          "trader_user_id": 1024,
          "customer_id": 482,
          "trader_class_id": null,
          "trader_class_schedule_id": null,
          "trader_class_package_id": 1,
          "name": "Test",
          "phone_number": null,
          "sub_total": 7.68,
          "service_fee": null,
          "taxes_fees": null,
          "total": 9.22,
          "start_date": "2020-11-27",
          "end_date": {
              "date": "2020-11-30 00:00:00.000000",
              "timezone_type": 3,
              "timezone": "Asia/Kolkata"
          },
          "start_time": null,
          "end_time": null,
          "subscription_type": null,
          "status": "Accepted-Paid",
          "commission_percentage": 10,
          "gst_percentage": 10,
          "created_at": "2020-03-24 14:47:58",
          "updated_at": "2020-03-24 14:48:01",
          "stripe_payment_intent_id": null,
          "stripe_payment_intent_status": "succeeded",
          "start_from": null,
          "class_count": 0,
          "unique_id": null,
          "pid": 0,
          "deleted_at": null,
          "customer_name": "",
          "customer_phone": "",
          "ending_date": "2020-11-30",
          "package_id": 1,
          "package_name": "Test 123",
          "package_description": "Gngfnh",
          "package_price": 7.68,
          "package_duration": "6-weeks",
          "package_class_count": 2,
          "package_quantity": 1,
          "package_available_from": "2020-11-01 00:00:00",
          "package_available_to": "2020-12-31 00:00:00",
          "package_total": 150,
          "trader_user": {
              "id": 1024,
              "name": "fitness test",
              "fname": "fitness",
              "lname": "test",
              "email": "fitness@gmail.com",
              "image": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg",
              "verification_code": "zEORtqYIpKgYJ3apQpVHbvtprWxELt",
              "status": 1,
              "_token": "",
              "seller_type": "fitness",
              "social_id": null,
              "login_type": "",
              "role_id": 0,
              "mobile_no": "7976764646",
              "mobile_no_verified": 1,
              "active_role_name": null,
              "location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "state": "",
              "city": "",
              "phonecode": "+61",
              "country": null,
              "latitude": null,
              "longitude": null,
              "pincode": "",
              "is_notification_active": 0,
              "is_survey_active": 0,
              "is_invites_active": 0,
              "is_newsletter_active": 0,
              "new_requested_email": null,
              "new_requested_email_status": 0,
              "email_updation_verification_code": null,
              "created_at": "2019-12-06 17:35:45",
              "updated_at": "2020-11-26 08:53:56",
              "avatar": null,
              "device_id": null,
              "device_model": null,
              "device_type": null,
              "os_version": null,
              "network_provider": null,
              "app_version_no": null,
              "business_name": "fitness vendor",
              "business_location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
              "business_state_id": "New South Wales",
              "business_city_id": "Port Macquarie",
              "business_pincode": "2444",
              "business_lat": "-31.429517899999997",
              "business_lng": "152.8961441",
              "business_suburb": null,
              "paypal_email": null,
              "stripe_customer_id": "",
              "braintree_id": null,
              "card_brand": null,
              "card_last_four": null,
              "payment_method_token": null,
              "trial_ends_at": null,
              "blocked": 0,
              "active": 1,
              "last_active": "2020-11-26 08:53:56",
              "profile_completed": 1,
              "braintree_nonce": "",
              "views": 2,
              "menu_skipped": 0,
              "image_thumbnail": "http://10.10.1.8/formee/upload_images/users/1024/49526.jpg"
          }
      }
  ]


  export const BOOKING_DETAILS = {
    "id": 2,
    "customer_id": 482,
    "trader_class_id": 13,
    "booking_type": "non-subscription-based",
    "quantity": 1,
    "status": "Accepted-Paid",
    "booking_date": "2020-03-09",
    "booking_time": "02:00:00",
    "sub_total": 222,
    "service_fee": 0,
    "taxes_fees": 0,
    "total": 266,
    "commission_percentage": 10,
    "gst_percentage": 10,
    "stripe_payment_intent_id": "pi_1GLpvJEcekv8Ig7dZwRpoh4M",
    "stripe_payment_intent_status": "succeeded",
    "stripe_transaction_fee": "6.94",
    "created_at": "2020-03-12 12:14:01",
    "updated_at": "2020-03-12 12:14:11",
    "subscription_unique_id": null,
    "cancellation_reason": null,
    "trader_user_id": 1024,
    "subscription_id": null,
    "deleted_at": null,
    "subscription": null,
    "vendor": {
      "id": 1024,
      "name": "fitness test",
      "image": "http://test.formee.co/upload_images/users/1024/49526.jpg",
      "business_lat": "-31.429517899999997",
      "business_lng": "152.8961441",
      "business_name": "fitness vendor",
      "business_location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
      "location": "195 Warlters St, Port Macquarie NSW 2444, Australia",
      "image_thumbnail": "http://test.formee.co/upload_images/users/1024/49526.jpg",
      "trader_profile": {
        "id": 315,
        "title": null,
        "user_id": 1024,
        "booking_cat_id": 3,
        "booking_sub_cat_id": 41,
        "trader_type": {
          "id": 3,
          "name": "Wellbeing"
        },
        "trader_service": {
          "id": 41,
          "name": "Fitness"
        }
      }
    },
    "customer": {
      "id": 482,
      "name": "Haris Mahmoud",
      "image_thumbnail": "http://test.formee.co/plugins/admin/dist/img/IMG_20200115_160859.JPG"
    },
    "trader_class": {
      "id": 13,
      "class_name": "Aerobic class",
      "instructor_name": "Talhaaaa",
      "room": "yy",
      "capacity": 36,
      "image": "http://test.formee.co/upload_images/wellbeing/fitness//5e2b00be5ccc5.png",
      "start_date": "12-03-2020",
      "end_date": "31-03-2020",
      "total_price": 0,
      "trader_ratings": []
    }
  }