export const CURRENT_ORDER = [
    {
      "status": "Cancelled",
      "id": 243,
      "user_id": 482,
      "order_subtotal": "56.00",
      "order_grandtotal": "65.53",
      "customer_fname": "Haris Mahmoud",
      "customer_lname": "Haris Mahmoud",
      "customer_address1": "Circular Quay East, Sydney, Australia",
      "customer_address2": "Circular Quay East, Sydney, Australia",
      "customer_city": "Sydney",
      "customer_state": "New South Wales",
      "customer_country": "Australia",
      "customer_postcode": "2000",
      "order_no": "11806",
      "order_type": "delivery",
      "created_at": "2020-03-19 10:43:08",
      "estimated_time": "40",
      "name": "Haris Mahmoud",
      "phone_number": "3164814847",
      "MP_order_payment_status": "PENDING",
      "repay_payment": 0,
      "restaurant_name": "Well bean restaurants",
      "restaurant_contact_number": "0321406916",
      "restaurant_contact_name": "allah rakha",
      "restaurant_address": "350 Bourke St, Melbourne VIC 3000, Australia",
      "is_payment_captured": 0,
      "order_status_display_vendor": "Cancelled",
      "order_status_display_user": "Cancelled",
      "current_status": {
        "id": 801,
        "restaurant_orders_id": 243,
        "status": "confirmed",
        "current_status": "1",
        "created_at": "2020-03-19 10:43:47",
        "updated_at": "2020-11-06 18:57:47",
        "changed_at": "2020-03-19 10:43:47"
      },
      "cancel_status": null
    },
    {
      "status": "Cancelled",
      "id": 242,
      "user_id": 482,
      "order_subtotal": "132.00",
      "order_grandtotal": "154.45",
      "customer_fname": "Haris Mahmoud",
      "customer_lname": "Haris Mahmoud",
      "customer_address1": "Circular Quay East, Sydney, Australia",
      "customer_address2": "Circular Quay East, Sydney, Australia",
      "customer_city": "Sydney",
      "customer_state": "New South Wales",
      "customer_country": "Australia",
      "customer_postcode": "2000",
      "order_no": "19753",
      "order_type": "delivery",
      "created_at": "2020-03-19 09:53:08",
      "estimated_time": "80",
      "name": "Haris Mahmoud",
      "phone_number": "3164814847",
      "MP_order_payment_status": "PENDING",
      "repay_payment": 0,
      "restaurant_name": "Well bean restaurants",
      "restaurant_contact_number": "0321406916",
      "restaurant_contact_name": "allah rakha",
      "restaurant_address": "350 Bourke St, Melbourne VIC 3000, Australia",
      "is_payment_captured": 0,
      "order_status_display_vendor": "Cancelled",
      "order_status_display_user": "Cancelled",
      "current_status": {
        "id": 795,
        "restaurant_orders_id": 242,
        "status": "confirmed",
        "current_status": "1",
        "created_at": "2020-03-19 10:43:47",
        "updated_at": "2020-11-06 18:55:47",
        "changed_at": "2020-03-19 10:43:47"
      },
      "cancel_status": null
    },
    {
      "status": "Cancelled",
      "id": 241,
      "user_id": 482,
      "order_subtotal": "980.00",
      "order_grandtotal": "1146.61",
      "customer_fname": "javed",
      "customer_lname": "iqbal",
      "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
      "customer_address2": "",
      "customer_city": "Riverstone",
      "customer_state": "New South Wales",
      "customer_country": "Australia",
      "customer_postcode": "2765",
      "order_no": "85871",
      "order_type": "take_away",
      "created_at": "2020-03-18 22:47:47",
      "estimated_time": "",
      "name": "Haris Mahmoud",
      "phone_number": "3164814847",
      "MP_order_payment_status": "PENDING",
      "repay_payment": 0,
      "restaurant_name": "Well bean restaurants",
      "restaurant_contact_number": "0321406916",
      "restaurant_contact_name": "allah rakha",
      "restaurant_address": "350 Bourke St, Melbourne VIC 3000, Australia",
      "is_payment_captured": 0,
      "order_status_display_vendor": "Cancelled",
      "order_status_display_user": "Cancelled",
      "current_status": {
        "id": 788,
        "restaurant_orders_id": 241,
        "status": "cancelled",
        "current_status": "1",
        "created_at": "2020-03-18 22:48:07",
        "updated_at": "2020-03-18 22:48:07",
        "changed_at": "2020-03-18 22:48:07"
      },
      "cancel_status": null
    },
    {
      "status": "Cancelled",
      "id": 240,
      "user_id": 482,
      "order_subtotal": "980.00",
      "order_grandtotal": "1146.61",
      "customer_fname": "javed",
      "customer_lname": "iqbal",
      "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
      "customer_address2": "",
      "customer_city": "Riverstone",
      "customer_state": "New South Wales",
      "customer_country": "Australia",
      "customer_postcode": "2765",
      "order_no": "86629",
      "order_type": "take_away",
      "created_at": "2020-03-10 22:32:49",
      "estimated_time": "60",
      "name": "Haris Mahmoud",
      "phone_number": "3164814847",
      "MP_order_payment_status": "PENDING",
      "repay_payment": 0,
      "restaurant_name": "Well bean restaurants",
      "restaurant_contact_number": "0321406916",
      "restaurant_contact_name": "allah rakha",
      "restaurant_address": "350 Bourke St, Melbourne VIC 3000, Australia",
      "is_payment_captured": 0,
      "order_status_display_vendor": "Cancelled",
      "order_status_display_user": "Cancelled",
      "current_status": {
        "id": 782,
        "restaurant_orders_id": 240,
        "status": "cancelled",
        "current_status": "1",
        "created_at": "2020-03-11 00:49:14",
        "updated_at": "2020-03-11 00:49:14",
        "changed_at": "2020-03-11 00:49:14"
      },
      "cancel_status": null
    },
    {
      "status": "Cancelled",
      "id": 230,
      "user_id": 482,
      "order_subtotal": "980.00",
      "order_grandtotal": "1146.61",
      "customer_fname": "javed",
      "customer_lname": "iqbal",
      "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
      "customer_address2": "",
      "customer_city": "Riverstone",
      "customer_state": "New South Wales",
      "customer_country": "Australia",
      "customer_postcode": "2765",
      "order_no": "30221",
      "order_type": "delivery",
      "created_at": "2020-03-06 09:54:22",
      "estimated_time": "60",
      "name": "Haris Mahmoud",
      "phone_number": "3164814847",
      "MP_order_payment_status": "PENDING",
      "repay_payment": 0,
      "restaurant_name": "Well bean restaurants",
      "restaurant_contact_number": "0321406916",
      "restaurant_contact_name": "allah rakha",
      "restaurant_address": "350 Bourke St, Melbourne VIC 3000, Australia",
      "is_payment_captured": 0,
      "order_status_display_vendor": "Cancelled",
      "order_status_display_user": "Cancelled",
      "current_status": {
        "id": 789,
        "restaurant_orders_id": 230,
        "status": "cancelled",
        "current_status": "1",
        "created_at": "2020-03-18 22:50:45",
        "updated_at": "2020-03-18 22:50:45",
        "changed_at": "2020-03-18 22:50:45"
      },
      "cancel_status": null
    },
    {
      "status": "Cancelled",
      "id": 151,
      "user_id": 482,
      "order_subtotal": "2940.00",
      "order_grandtotal": "3439.81",
      "customer_fname": "javed",
      "customer_lname": "iqbal",
      "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
      "customer_address2": "",
      "customer_city": "Riverstone",
      "customer_state": "New South Wales",
      "customer_country": "Australia",
      "customer_postcode": "2765",
      "order_no": "68626",
      "order_type": "delivery",
      "created_at": "2020-03-03 10:10:16",
      "estimated_time": "",
      "name": "Haris Mahmoud",
      "phone_number": "3164814847",
      "MP_order_payment_status": "PENDING",
      "repay_payment": 0,
      "restaurant_name": "Well bean restaurants",
      "restaurant_contact_number": "0321406916",
      "restaurant_contact_name": "allah rakha",
      "restaurant_address": "350 Bourke St, Melbourne VIC 3000, Australia",
      "is_payment_captured": 0,
      "order_status_display_vendor": "Cancelled",
      "order_status_display_user": "Cancelled",
      "current_status": {
        "id": 491,
        "restaurant_orders_id": 151,
        "status": "cancelled",
        "current_status": "1",
        "created_at": "2020-03-03 10:13:12",
        "updated_at": "2020-03-03 10:13:12",
        "changed_at": "2020-03-03 10:13:12"
      },
      "cancel_status": null
    },
    {
      "status": "Cancelled",
      "id": 149,
      "user_id": 482,
      "order_subtotal": "56.00",
      "order_grandtotal": "65.53",
      "customer_fname": "Haris Mahmoud",
      "customer_lname": "Haris Mahmoud",
      "customer_address1": "Circular Quay East, Sydney, Australia",
      "customer_address2": "Circular Quay East, Sydney, Australia",
      "customer_city": "Sydney",
      "customer_state": "New South Wales",
      "customer_country": "Australia",
      "customer_postcode": "2000",
      "order_no": "75145",
      "order_type": "take_away",
      "created_at": "2020-03-03 10:04:40",
      "estimated_time": "",
      "name": "Haris Mahmoud",
      "phone_number": "3164814847",
      "MP_order_payment_status": "PENDING",
      "repay_payment": 0,
      "restaurant_name": "Well bean restaurants",
      "restaurant_contact_number": "0321406916",
      "restaurant_contact_name": "allah rakha",
      "restaurant_address": "350 Bourke St, Melbourne VIC 3000, Australia",
      "is_payment_captured": 0,
      "order_status_display_vendor": "Cancelled",
      "order_status_display_user": "Cancelled",
      "current_status": {
        "id": 485,
        "restaurant_orders_id": 149,
        "status": "cancelled",
        "current_status": "1",
        "created_at": "2020-03-03 10:05:00",
        "updated_at": "2020-03-03 10:05:00",
        "changed_at": "2020-03-03 10:05:00"
      },
      "cancel_status": null
    },
    {
      "status": "Cancelled",
      "id": 148,
      "user_id": 482,
      "order_subtotal": "3931.00",
      "order_grandtotal": "4599.30",
      "customer_fname": "Haris Mahmoud",
      "customer_lname": "Haris Mahmoud",
      "customer_address1": "Circular Quay East, Sydney, Australia",
      "customer_address2": "Circular Quay East, Sydney, Australia",
      "customer_city": "Sydney",
      "customer_state": "New South Wales",
      "customer_country": "Australia",
      "customer_postcode": "2000",
      "order_no": "18572",
      "order_type": "take_away",
      "created_at": "2020-03-03 10:02:47",
      "estimated_time": "",
      "name": "Haris Mahmoud",
      "phone_number": "3164814847",
      "MP_order_payment_status": "PENDING",
      "repay_payment": 0,
      "restaurant_name": "Well bean restaurants",
      "restaurant_contact_number": "0321406916",
      "restaurant_contact_name": "allah rakha",
      "restaurant_address": "350 Bourke St, Melbourne VIC 3000, Australia",
      "is_payment_captured": 0,
      "order_status_display_vendor": "Cancelled",
      "order_status_display_user": "Cancelled",
      "current_status": {
        "id": 479,
        "restaurant_orders_id": 148,
        "status": "cancelled",
        "current_status": "1",
        "created_at": "2020-03-03 10:03:40",
        "updated_at": "2020-03-03 10:03:40",
        "changed_at": "2020-03-03 10:03:40"
      },
      "cancel_status": null
    },
    {
      "status": "Cancelled",
      "id": 126,
      "user_id": 482,
      "order_subtotal": "316.00",
      "order_grandtotal": "369.74",
      "customer_fname": "javed",
      "customer_lname": "iqbal",
      "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
      "customer_address2": "",
      "customer_city": "Riverstone",
      "customer_state": "New South Wales",
      "customer_country": "Australia",
      "customer_postcode": "2765",
      "order_no": "64707",
      "order_type": "delivery",
      "created_at": "2020-03-02 14:48:23",
      "estimated_time": "",
      "name": "Haris Mahmoud",
      "phone_number": "3164814847",
      "MP_order_payment_status": "PENDING",
      "repay_payment": 0,
      "restaurant_name": "Well bean restaurants",
      "restaurant_contact_number": "0321406916",
      "restaurant_contact_name": "allah rakha",
      "restaurant_address": "350 Bourke St, Melbourne VIC 3000, Australia",
      "is_payment_captured": 0,
      "order_status_display_vendor": "Cancelled",
      "order_status_display_user": "Cancelled",
      "current_status": {
        "id": 462,
        "restaurant_orders_id": 126,
        "status": "cancelled",
        "current_status": "1",
        "created_at": "2020-03-02 14:52:09",
        "updated_at": "2020-03-02 14:52:09",
        "changed_at": "2020-03-02 14:52:09"
      },
      "cancel_status": null
    },
    {
      "status": "Cancelled",
      "id": 124,
      "user_id": 482,
      "order_subtotal": "840.00",
      "order_grandtotal": "982.82",
      "customer_fname": "javed",
      "customer_lname": "iqbal",
      "customer_address1": "house 5 street 9 yateem khana lari adda lahore",
      "customer_address2": "",
      "customer_city": "Riverstone",
      "customer_state": "New South Wales",
      "customer_country": "Australia",
      "customer_postcode": "2765",
      "order_no": "83983",
      "order_type": "delivery",
      "created_at": "2020-03-02 14:33:29",
      "estimated_time": "",
      "name": "Haris Mahmoud",
      "phone_number": "3164814847",
      "MP_order_payment_status": "PENDING",
      "repay_payment": 0,
      "restaurant_name": "Vegetarian Food Corner New",
      "restaurant_contact_number": "8896800983",
      "restaurant_contact_name": "Mohit",
      "restaurant_address": "Vikas Marg Chandigarh India",
      "is_payment_captured": 0,
      "order_status_display_vendor": "Cancelled",
      "order_status_display_user": "Cancelled",
      "current_status": {
        "id": 463,
        "restaurant_orders_id": 124,
        "status": "cancelled",
        "current_status": "1",
        "created_at": "2020-03-03 07:01:28",
        "updated_at": "2020-03-03 07:01:28",
        "changed_at": "2020-03-03 07:01:28"
      },
      "cancel_status": null
    }
  ];

  export const ORDER_DETAIL =  {
      "id":230,
      "created_at":"2020-03-06 09:54:22",
      "order_no":"30221",
      "order_commission_amount":"0.01",
      "order_gst_amount":"166.60",
      "customer_fname":"javed",
      "customer_lname":"iqbal",
      "customer_address1":"house 5 street 9 yateem khana lari adda lahore",
      "customer_address2":"",
      "customer_city":"Riverstone",
      "customer_state":"New South Wales",
      "customer_country":"Australia",
      "customer_postcode":"2765",
      "order_type":"delivery",
      "order_grandtotal":"1146.61",
      "order_subtotal":"980.00",
      "name":"Haris Mahmoud",
      "phone_number":"3164814847",
      "estimated_time":"60",
      "restaurant_name":"test66ewew business",
      "restaurant_contact_number":"8766454556443",
      "restaurant_contact_name":"test66twt contact detail",
      "restaurant_address":"test1 test66 ",
      "pickup_time":"2020-03-06 15:24:21",
      "MP_order_payment_status":"PENDING",
      "rating":0,
      "disputed":0,
      "all_status":[
        {
          "status":"order-received",
          "changed_at":"2020-03-06 09:54:25",
          "order_status_display_vendor":"order-received",
          "order_status_display_user":"order-received"
        },
        {
          "status":"confirmed",
          "changed_at":"2020-11-05 05:49:48",
          "order_status_display_vendor":"confirmed",
          "order_status_display_user":"confirmed"
        },
        {
          "status":"in-the-kitchen",
          "changed_at": null,
          "order_status_display_vendor":"in-the-kitchen",
          "order_status_display_user":"in-the-kitchen"
        },
        {
          "status":"on-the-way",
          "changed_at": null,
          "order_status_display_vendor":"on-the-way",
          "order_status_display_user":"on-the-way"
        },
        {
          "status":"delivered",
          "changed_at": null,
          "order_status_display_vendor":"delivered",
          "order_status_display_user":"delivered"
        },
        {
          "status":"cancelled",
          "changed_at":"2020-03-18 22:50:45",
          "order_status_display_vendor":"cancelled",
          "order_status_display_user":"cancelled"
        }
      ],
      "order-received":"2020-03-06 09:54:25",
      "confirmed":"2020-11-05 05:49:48",
      "in-the-kitchen":"",
      "on-the-way":"",
      "delivered":"",
      "cancelled":"2020-03-18 22:50:45",
      "is_payment_captured":0,
      "order_status_display_vendor":null,
      "order_status_display_user":null,
      "order_detail":[
      ]
    }