export const DASHBOARD_LISTING = {
            "classified": [
                {
                    "id": 75,
                    "title": "Blackboard Chalkboard Medium Black Timber Wooden Frame",
                    "subject": "Make an Offer",
                    "massage": "Hi there, I'd like to offer $200",
                    "offer_price": 200,
                    "status": "Pending",
                    "category_name": "Home & Garden",
                    "sub_category_name": "Home Decor ",
                    "business_name": null,
                    "parent_categoryid": 41,
                    "category_id": 54,
                    "created_at": "2020-12-04 14:51:58",
                    "activity_type": "Offer Sent",
                    "module_type": "Classified"
                },
                {
                    "id": 79,
                    "title": "test car",
                    "subject": "Make an Offer",
                    "massage": "Hi there, I'd like to offer $545",
                    "offer_price": 545,
                    "status": "Pending",
                    "category_name": "Automotive",
                    "sub_category_name": "Cars & Vans",
                    "business_name": null,
                    "parent_categoryid": 30,
                    "category_id": 31,
                    "created_at": "2020-12-04 14:51:58",
                    "activity_type": "Offer Sent",
                    "module_type": "Classified"
                },
                {
                    "id": 29,
                    "title": "Psychologist",
                    "customer_id": 485,
                    "status": "",
                    "category_name": "Jobs",
                    "sub_category_name": "Healthcare & Nursing ",
                    "business_name": null,
                    "parent_categoryid": 37,
                    "category_id": 65,
                    "created_at": "2020-12-04 14:20:30",
                    "activity_type": "Applied Job",
                    "module_type": "Classified"
                },
                {
                    "id": 30,
                    "title": "Looking for a Change from Hospitality?",
                    "customer_id": 485,
                    "status": "",
                    "category_name": "Jobs",
                    "sub_category_name": "  Hospitality & Tourism ",
                    "business_name": null,
                    "parent_categoryid": 37,
                    "category_id": 66,
                    "created_at": "2020-12-03 14:24:46",
                    "activity_type": "Applied Job",
                    "module_type": "Classified"
                }
            ],
            "booking": [
                {
                    "id": 1,
                    "title": "Engagement",
                    "description": "",
                    "price": 1000,
                    "start_date": "2020-12-03 11:00:00",
                    "end_date": "2020-12-03 13:00:00",
                    "status": "Accepted-Paid",
                    "category_name": "Events",
                    "sub_category_name": "Caterers",
                    "time": "2019-07-26 19:00:00",
                    "booking_date": "2020-12-03",
                    "business_name": "Test profile business",
                    "trader_user_id": 894,
                    "trader_profile_id": 222,
                    "customer_id": 485,
                    "booking_cat_id": 31,
                    "booking_sub_cat_id": 33,
                    "event_type_id": 6,
                    "additional_comments": "asdasdasd",
                    "activity_type": "Event Booked",
                    "module_type": "Booking",
                    "total_days": 1
                },
                {
                    "id": 2,
                    "title": "Engagement",
                    "description": "",
                    "price": 1000,
                    "start_date": "2020-12-10 16:00:00",
                    "end_date": "2020-12-10 17:00:00",
                    "status": "Accepted-Paid",
                    "category_name": "Events",
                    "sub_category_name": "Caterers",
                    "time": "2019-07-26 19:00:00",
                    "booking_date": "2020-12-10",
                    "business_name": "Test profile business",
                    "trader_user_id": 894,
                    "trader_profile_id": 222,
                    "customer_id": 485,
                    "booking_cat_id": 31,
                    "booking_sub_cat_id": 33,
                    "event_type_id": 6,
                    "additional_comments": "asdasdasd",
                    "activity_type": "Event Booked",
                    "module_type": "Booking",
                    "total_days": 1
                },
                {
                    "id": 11,
                    "title": "same date Class",
                    "description": "test",
                    "booking_date": "2020-12-29",
                    "start_time": "01:00:00",
                    "end_time": "02:00:00",
                    "status": "Pending",
                    "total_time": "60 Minutes",
                    "business_name": "Formee Fitness Vendor",
                    "trader_user_id": 917,
                    "trader_class_id": 72,
                    "customer_id": 485,
                    "type": "non-subscription-based",
                    "price": 54,
                    "activity_type": "Class Booked",
                    "module_type": "Booking"
                },
                {
                    "id": 4,
                    "title": "Vegetarian Food Corner New",
                    "description": "<p>Veg reataturent with amazing dishes</p>",
                    "booking_date": "2020-12-29 20:05:16",
                    "status": "Cancelled",
                    "business_name": "Business Name test",
                    "business_profile_id": 22,
                    "user_id": 485,
                    "type": "take_away",
                    "price": "421.21",
                    "order_no": "64307",
                    "activity_type": "Restaurant Order",
                    "module_type": "Booking",
                    "order_status_display_vendor": "Cancelled",
                    "order_status_display_user": "Cancelled"
                },
                {
                    "id": 5,
                    "title": "Vegetarian Food Corner New",
                    "description": "<p>Veg reataturent with amazing dishes</p>",
                    "booking_date": "2020-12-29 20:05:16",
                    "status": "Completed",
                    "business_name": "Business Name test",
                    "business_profile_id": 22,
                    "user_id": 485,
                    "type": "take_away",
                    "price": "702.02",
                    "order_no": "49910",
                    "activity_type": "Restaurant Order",
                    "module_type": "Booking",
                    "order_status_display_vendor": "Completed",
                    "order_status_display_user": "Completed"
                },
                {
                    "id": 6,
                    "title": "Vegetarian Food Corner New",
                    "description": "<p>Veg reataturent with amazing dishes</p>",
                    "booking_date": "2020-12-28 20:05:16",
                    "status": "Completed",
                    "business_name": "Business Name test",
                    "business_profile_id": 22,
                    "user_id": 485,
                    "type": "take_away",
                    "price": "702.02",
                    "order_no": "59000",
                    "activity_type": "Restaurant Order",
                    "module_type": "Booking",
                    "order_status_display_vendor": "Completed",
                    "order_status_display_user": "Completed"
                },
                {
                    "id": 7,
                    "title": "test66ewew business",
                    "description": "test1 test66 ",
                    "booking_date": "2020-12-25 20:05:16",
                    "status": "Accepted",
                    "business_name": "Business Name test",
                    "business_profile_id": 2,
                    "user_id": 485,
                    "type": "take_away",
                    "price": "7704.86",
                    "order_no": "22505",
                    "activity_type": "Restaurant Order",
                    "module_type": "Booking",
                    "order_status_display_vendor": "Accepted",
                    "order_status_display_user": "Accepted"
                },
                {
                    "id": 10,
                    "title": "Vegetarian Food Corner New",
                    "description": "<p>Veg reataturent with amazing dishes</p>",
                    "booking_date": "2020-12-20 20:05:16",
                    "status": "Completed",
                    "business_name": "Business Name test",
                    "business_profile_id": 22,
                    "user_id": 485,
                    "type": "take_away",
                    "price": "514.81",
                    "order_no": "12471",
                    "activity_type": "Restaurant Order",
                    "module_type": "Booking",
                    "order_status_display_vendor": "Completed",
                    "order_status_display_user": "Completed"
                }
            ],
            "retail": [
                {
                    "id": 204,
                    "title": "iPhone 8 Plus",
                    "description": "<p>Its new iPhone 8 Plus 64GB.</p>",
                    "created_at": "2020-12-05 15:45:27",
                    "status": "pending",
                    "business_name": "Elastic Brainz",
                    "user_id": 485,
                    "price": "0.00",
                    "activity_type": "Retail Order",
                    "module_type": "Retail"
                },
                {
                    "id": 207,
                    "title": "Lenovo g50",
                    "description": "nwicnciencjevje veu v",
                    "created_at": "2020-12-04 23:49:41",
                    "status": "Delivered",
                    "business_name": "Talha Naeem",
                    "user_id": 485,
                    "price": "150.00",
                    "activity_type": "Retail Order",
                    "module_type": "Retail"
                }
            ]
}